
[[commands]]
== Commands

The first argument (_cb_) of all the following functions is a <<command_buffer, command_buffer>>. 
////
The functions are also available as methods with the same name except for the trailing 'cmd_'. 
For example, _cb_++++*:bind_pipeline*(_..._) is the same as *vk.cmd_bind_pipeline*(_cb_, _..._).
////

[[cmd_begin_conditional_rendering]]
* *cmd_begin_conditional_rendering*(_cb_, <<conditionalrenderingbegininfo, _conditionalrenderingbegininfo_>>) +
*cmd_end_conditional_rendering*(_cb_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBeginConditionalRenderingEXT.html[vkCmdBeginConditionalRenderingEXT], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdEndConditionalRenderingEXT.html[vkCmdEndConditionalRenderingEXT].#

[[cmd_begin_debug_utils_label]]
* *cmd_begin_debug_utils_label*(_cb_, <<debugutilslabel, _debugutilslabel_>>) +
*cmd_end_debug_utils_label*(_cb_) +
*cmd_insert_debug_utils_label*(_cb_, <<debugutilslabel, _debugutilslabel_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBeginDebugUtilsLabelEXT.html[vkCmdBeginDebugUtilsLabelEXT], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdEndDebugUtilsLabelEXT.html[vkCmdEndDebugUtilsLabelEXT], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdInsertDebugUtilsLabelEXT.html[vkCmdInsertDebugUtilsLabelEXT].#

[[cmd_begin_query]]
* *cmd_begin_query*(_cb_, <<query_pool, _query_pool_>>, _query_, <<querycontrolflags, _querycontrolflags_>>) +
*cmd_end_query*(_cb_, <<query_pool, _query_pool_>>, _query_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBeginQuery.html[vkCmdBeginQuery], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdEndQuery.html[vkCmdEndQuery].#

[[cmd_begin_query_indexed]]
* *cmd_begin_query_indexed*(_cb_, <<query_pool, _query_pool_>>, _query_, <<querycontrolflags, _querycontrolflags_>>, _index_) +
*cmd_end_query_indexed*(_cb_, <<query_pool, _query_pool_>>, _query_, _index_) +
[small]#Rfr:
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBeginQueryIndexedEXT.html[vkCmdBeginQueryIndexedEXT], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdEndQueryIndexedEXT.html[vkCmdEndQueryIndexedEXT].#

[[cmd_begin_render_pass]]
* *cmd_begin_render_pass*(_cb_, <<renderpassbegininfo, _renderpassbegininfo_>>, <<subpasscontents, _subpasscontents_>>) +
*cmd_begin_render_pass*(_cb_, <<renderpassbegininfo, _renderpassbegininfo_>>, <<subpassbegininfo, _subpassbegininfo_>>) (2KHR) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBeginRenderPass.html[vkCmdBeginRenderPass], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBeginRenderPass2.html[vkCmdBeginRenderPass2].#

[[cmd_next_subpass]]
* *cmd_next_subpass*(_cb_, <<subpasscontents, _subpasscontents_>>) +
*cmd_next_subpass*(_cb_, <<subpassbegininfo, _subpassbegininfo_>>, <<subpassendinfo, _subpassendinfo_>>) (2KHR) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdNextSubpass.html[vkCmdNextSubpass], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdNextSubpass2.html[vkCmdNextSubpass2].#

[[cmd_end_render_pass]]
* *cmd_end_render_pass*(_cb_) +
*cmd_end_render_pass*(_cb_, <<subpassendinfo, _subpassendinfo_>>) (2KHR) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdEndRenderPass.html[vkCmdEndRenderPass], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdEndRenderPass2.html[vkCmdEndRenderPass2].#

[[cmd_begin_transform_feedback]]
* *cmd_begin_transform_feedback*(_cb_, _first_, [_buffers_], [_offsets_]) +
*cmd_end_transform_feedback*(_cb_, _first_, [_buffers_], [_offsets_]) +
[small]#_first_: integer (0-based), +
_buffers_: {<<buffer, buffer>>}, +
_offsets_: {integer}, +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBeginTransformFeedbackEXT.html[vkCmdBeginTransformFeedbackEXT], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdEndTransformFeedbackEXT.html[vkCmdEndTransformFeedbackEXT].#

[[cmd_bind_descriptor_sets]]
* *cmd_bind_descriptor_sets*(_cb_,  <<pipelinebindpoint, _pipelinebindpoint_>>, _..._) +
[small]#arg3 - _layout_: <<pipeline_layout, pipeline_layout>> +
arg4 - _first_set_: integer +
arg5 - _descriptor_sets_: {<<descriptor_set, descriptor_set>>} +
arg6 - [_dynamic_offsets_]: {integer} +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBindDescriptorSets.html[vkCmdBindDescriptorSets].#

[[cmd_bind_index_buffer]]
* *cmd_bind_index_buffer*(_cb_, <<buffer, _buffer_>>, _offset_, <<indextype, _indextype_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBindIndexBuffer.html[vkCmdBindIndexBuffer].#

[[cmd_bind_pipeline]]
* *cmd_bind_pipeline*(_cb_, <<pipelinebindpoint, _pipelinebindpoint_>>, <<pipeline, _pipeline_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBindPipeline.html[vkCmdBindPipeline].#

[[cmd_bind_transform_feedback_buffers]]
* *cmd_bind_transform_feedback_buffers*(_cb_, _first_binding_, _buffers_, [_offsets_], [_sizes_]) +
[small]#_first_binding_: integer (0-based), +
_buffers_: {<<buffer, buffer>>}, +
_offsets_: {integer}, +
_sizes_: {<<devicesize, devicesize>>}, +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBindTransformFeedbackBuffersEXT.html[vkCmdBindTransformFeedbackBuffersEXT].#

[[cmd_bind_vertex_buffers]]
* *cmd_bind_vertex_buffers*(_cb_, _first_binding_, {<<buffer, _buffer_>>}, {_offsets_}) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBindVertexBuffers.html[vkCmdBindVertexBuffers].#

[[cmd_blit_image]]
* *cmd_blit_image*(_cb_, _src_image_, _..._) +
*cmd_blit_image*(_cb_, <<blitimageinfo, _blitimageinfo_>>) (2KHR) +
[small]#arg2 - _src_image_: <<image, image>> +
arg3 - _src_imagelayout_: <<imagelayout, imagelayout>> +
arg4 - _dst_image_: <<image, image>> +
arg5 - _dst_imagelayout_: <<imagelayout, imagelayout>> +
arg6 - _regions_ : {<<imageblit, imageblit>>} +
arg7 - _filter_: <<filter, filter>> +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBlitImage.html[vkCmdBlitImage], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBlitImage2KHR.html[vkCmdBlitImage 2KHR].#

[[cmd_clear_attachments]]
* *cmd_clear_attachments*(_cb_, _attachments_, _rects_) +
[small]#_attachments_: {<<clearattachment, clearattachment>>} +
_rects_: {<<clearrect, clearrect>>} +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdClearAttachments.html[vkCmdClearAttachments].#

[[cmd_clear_color_image]]
* *cmd_clear_color_image*(_cb_, _image_, _imagelayout_, _color_, _ranges_) +
[small]#_image_: <<image, image>> +
_imagelayout_: <<imagelayout, imagelayout>> +
_color_: <<clearcolorvalue, clearcolorvalue>> +
_ranges_: {<<imagesubresourcerange, imagesubresourcerange>>} +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdClearColorImage.html[vkCmdClearColorImage].#

[[cmd_clear_depth_stencil_image]]
* *cmd_clear_depth_stencil_image*(_cb_, _image_, _imagelayout_, _depth_, _stencil_, _ranges_) +
[small]#_image_: <<image, image>> +
_imagelayout_: <<imagelayout, imagelayout>> +
_depth_: _float_ +
_stencil_: _integer_ +
_ranges_: {<<imagesubresourcerange, imagesubresourcerange>>} +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdClearDepthStencilImage.html[vkCmdClearDepthStencilImage].#

[[cmd_copy_buffer]]
* *cmd_copy_buffer*(_cb_, _src_buffer_, _dst_buffer_, _regions_) +
*cmd_copy_buffer*(_cb_, <<copybufferinfo, _copybufferinfo_>>) (2KHR) +
[small]#_src_buffer_: <<buffer, buffer>> +
_dst_buffer_: <<buffer, buffer>> +
_regions_: {<<buffercopy, buffercopy>>} +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdCopyBuffer.html[vkCmdCopyBuffer], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdCopyBuffer2KHR.html[vkCmdCopyBuffer2KHR].#

[[cmd_copy_buffer_to_image]]
* *cmd_copy_buffer_to_image*(_cb_, _src_buffer_, _dst_image_, _dst_imagelayout_, _regions_) +
*cmd_copy_buffer_to_image*(_cb_, <<copybuffertoimageinfo, _copybuffertoimageinfo_>>) (2KHR) +
[small]#_src_buffer_: <<buffer, buffer>> +
_dst_image_: <<image, image>> +
_dst_imagelayout_: <<imagelayout, imagelayout>> +
_regions_: {<<bufferimagecopy, bufferimagecopy>>} +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdCopyBufferToImage.html[vkCmdCopyBufferToImage], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdCopyBufferToImage2KHR.html[vkCmdCopyBufferToImage 2KHR].#

[[cmd_copy_image]]
* *cmd_copy_image*(_cb_, _src_image_, _..._) +
*cmd_copy_image*(_cb_, <<copyimageinfo, _copyimageinfo_>>) (2KHR) +
[small]#arg2 - _src_image_: <<image, image>> +
arg3 - _src_imagelayout_: <<imagelayout, imagelayout>> +
arg4 - _dst_image_: <<image, image>> +
arg5 - _dst_imagelayout_: <<imagelayout, imagelayout>> +
arg6 - _regions_ : {<<imagecopy, imagecopy>>} +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdCopyImage.html[vkCmdCopyImage], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdCopyImage2KHR.html[vkCmdCopyImage2KHR].#


[[cmd_copy_image_to_buffer]]
* *cmd_copy_image_to_buffer*(_cb_, _src_image_, _..._) +
*cmd_copy_image_to_buffer*(_cb_, <<copyimagetobufferinfo, _copyimagetobufferinfo_>>) (2KHR) +
[small]#arg2 - _src_image_: <<image, image>> +
arg3 - _src_imagelayout_: <<imagelayout, imagelayout>> +
arg4 - _dst_buffer_: <<buffer, buffer>> +
arg5 - _regions_: {<<bufferimagecopy, bufferimagecopy>>} +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdCopyImageToBuffer.html[vkCmdCopyImageToBuffer], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdCopyImageToBuffer2KHR.html[vkCmdCopyImageToBuffer2KHR].#

[[cmd_copy_query_pool_results]]
* *cmd_copy_query_pool_results*(_cb_, _query_pool_, _..._) +
[small]#arg2 - _query_pool_: <<query_pool, query_pool>> +
arg3 - _first_query_: integer +
arg4 - _query_count_: integer +
arg5 - _dst_buffer_: <<buffer, buffer>> +
arg6 - _dst_offset_: integer +
arg7 - _stride_: integer +
arg8 - _flags_: <<queryresultflags, queryresultflags>> +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdCopyQueryPoolResults.html[vkCmdCopyQueryPoolResults].#

[[cmd_debug_marker_begin]]
* *cmd_debug_marker_begin*(_cb_, _marker_name_, [_color_]) +
*cmd_debug_marker_end*(_cb_) +
*cmd_debug_marker_insert*(_cb_, _marker_name_, [_color_]) +
[small]#_marker_name_: string +
_color_: {float}[4] (opt.) +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdDebugMarkerBeginEXT.html[vkCmdDebugMarkerBeginEXT],
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdDebugMarkerEndEXT.html[vkCmdDebugMarkerEndEXT],
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdDebugMarkerInsertEXT.html[vkCmdDebugMarkerInsertEXT]#.

[[cmd_dispatch]]
* *cmd_dispatch*(_cb_, _x_, _y_, _z_) +
*cmd_dispatch_indirect*(_cb_, <<buffer, _buffer_>>, _offset_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdDispatch.html[vkCmdDispatch],
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdDispatchIndirect.html[vkCmdDispatchIndirect].#

[[cmd_dispatch_base]]
* *cmd_dispatch_base*(_cb_, _basegroup_x_, _basegroup_y_, _basegroup_z_, _groupcount_x_, _groupcount_y_, _groupcount_z_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdDispatchBase.html[vkCmdDispatchBase].#


[[cmd_draw]]
* *cmd_draw*(_cb_, _vertex_count_, _instance_count_, _first_vertex_, _first_instance_) +
*cmd_draw_indexed*(_cb_, _index_count_, _instance_count_, _first_index_, _vertex_offset_, _first_instance_) +
*cmd_draw_indexed_indirect*(_cb_, <<buffer, _buffer_>>, _offset_, _draw_count_, _stride_) +
*cmd_draw_indirect*(_cb_, <<buffer, _buffer_>>, _offset_, _draw_count_, _stride_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdDraw.html[vkCmdDraw],
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdDrawIndexed.html[vkCmdDrawIndexed],
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdDrawIndexedIndirect.html[vkCmdDrawIndexedIndirect],
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdDrawIndirect.html[vkCmdDrawIndirect].#

[[cmd_draw_indirect_byte_count]]
* *cmd_draw_indirect_byte_count*(_cb_, _instance_count_, _first_instance_, <<buffer, _counter_buffer_>>, _counter_buffer_offset_, _counter_offset_, _vertex_stride_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdDrawIndirectByteCountEXT.html[vkCmdDrawIndirectByteCountEXT].#

[[cmd_draw_indirect_count]]
* *cmd_draw_indirect_count*(_cb_, <<buffer, _buffer_>>, _offset_, <<buffer, _count_buffer_>>, _count_buffer_offset_, _max_draw_count_, _stride_) +
*cmd_draw_indexed_indirect_count*(_cb_, <<buffer, _buffer_>>, _offset_, <<buffer, _count_buffer_>>, _count_buffer_offset_, _max_draw_count_, _stride_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdDrawIndirectCount.html[vkCmdDrawIndirectCount],
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdDrawIndexedIndirectCount.html[vkCmdDrawIndexedIndirectCount],.#

[[cmd_execute_commands]]
* *cmd_execute_commands*(_cb_, {<<command_buffer, _command_buffer_>>}) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdExecuteCommands.html[vkCmdExecuteCommands].#

[[cmd_fill_buffer]]
* *cmd_fill_buffer*(_cb_, _dst_buffer_, _dst_offset_, _size_, _data_) +
[small]#_dst_buffer_: <<buffer, buffer>> +
_dst_offset_: integer +
_size_: integer (multiple of 4) or '_whole size_' +
_data_: integer +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdFillBuffer.html[vkCmdFillBuffer].#

[[cmd_pipeline_barrier]]
* *cmd_pipeline_barrier*(_cb_, _src_stage_mask_, _..._) +
[small]#arg2 - _src_stage_mask_: <<pipelinestageflags, pipelinestageflags>> +
arg3 - _dst_stage_mask_: <<pipelinestageflags, pipelinestageflags>> +
arg4 - _dependency_flags_: <<dependencyflags, dependencyflags>> +
arg5 - [_memory_barriers_]: {<<memorybarrier, memorybarrier>>} +
arg6 - [_buffer_memory_barriers_]: {<<buffermemorybarrier, buffermemorybarrier>>} +
arg7 - [_image_memory_barriers_]: {<<imagememorybarrier, imagememorybarrier>>} +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdPipelineBarrier.html[vkCmdPipelineBarrier].#

[[cmd_push_descriptor_set]]
* *cmd_push_descriptor_set*(_cb_, _bind_point_, _..._) +
[small]#arg2 - _bind_point_: <<pipelinebindpoint, pipelinebindpoint>> +
arg3 - _pipeline_layout_: <<pipeline_layout, pipeline_layout>> +
arg4 - _set_: integer +
arg5 - _writes_: {<<writedescriptorset, writedescriptorset>>} +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdPushDescriptorSetKHR.html[vkCmdPushDescriptorSetKHR].#

[[cmd_push_descriptor_set_with_template]]
* *cmd_push_descriptor_set_with_template*(_cb_, _descriptor_update_template_, _layout_, _..._) +
[small]#arg3: _layout_: <<pipeline_layout, pipeline_layout>> +
arg4: _set_: integer +
arg5: _data_: binary string +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdPushDescriptorSetWithTemplateKHR.html[vkCmdPushDescriptorSetWithTemplateKHR].#

[[cmd_push_constants]]
* *cmd_push_constants*(_cb_, _layout_, _flags_, _offset_, _values_) +
[small]#_layout_: <<pipeline_layout, pipeline_layout>> +
_flags_: <<shaderstageflags, shaderstageflags>> +
_offset_: integer +
_values_: binary string +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdPushConstants.html[vkCmdPushConstants].#

[[cmd_reset_event]]
* *cmd_reset_event*(_cb_, <<event, _event_>>, <<pipelinestageflags, _pipelinestageflags_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdResetEvent.html[vkCmdResetEvent].#

[[cmd_reset_query_pool]]
* *cmd_reset_query_pool*(_cb_, <<query_pool, _query_pool_>>, _first_query_, _query_count_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdResetQueryPool.html[vkCmdResetQueryPool].#

[[cmd_resolve_image]]
* *cmd_resolve_image*(_cb_, _src_image_, _..._) +
*cmd_resolve_image*(_cb_, <<resolveimageinfo, _resolveimageinfo_>>) (2KHR) +
[small]#arg2 - _src_image_: <<image, image>> +
arg3 - _src_imagelayout_: <<imagelayout, imagelayout>> +
arg4 - _dst_image_: <<image, image>> +
arg5 - _dst_imagelayout_: <<imagelayout, imagelayout>> +
arg6 - _regions_: {<<imageresolve, imageresolve>>} +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdResolveImage.html[vkCmdResolveImage], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdResolveImage2KHR.html[vkCmdResolveImage2KHR].#

[[cmd_set_blend_constants]]
* *cmd_set_blend_constants*(_cb_, _constant~0~_, _constant~1~_, _constant~2~_, _constant~3~_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetBlendConstants.html[vkCmdSetBlendConstants].#

[[cmd_set_color_write_enable]]
* *cmd_set_color_write_enable*(_cb_, {_boolean_}) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetColorWriteEnableEXT.html[vkCmdSetColorWriteEnableEXT].#

[[cmd_set_depth_bias]]
* *cmd_set_depth_bias*(_cb_, _constantfactor_, _clamp_, _slopefactor_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetDepthBias.html[vkCmdSetDepthBias].#

[[cmd_set_depth_bounds]]
* *cmd_set_depth_bounds*(_cb_, _min_, _max_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetDepthBounds.html[vkCmdSetDepthBounds].#

[[cmd_set_device_mask]]
* *cmd_set_device_mask*(_cb_, _devicemask_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetDeviceMask.html[vkCmdSetDeviceMask].#

[[cmd_set_discard_rectangle]]
* *cmd_set_discard_rectangle*(_cb_, _first_, {<<rect2d, _rect2d_>>}) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetDiscardRectangleEXT.html[vkCmdSetDiscardRectangleEXT].#

[[cmd_set_event]]
* *cmd_set_event*(_cb_, <<event, _event_>>, <<pipelinestageflags, _pipelinestageflags_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetEvent.html[vkCmdSetEvent].#

[[cmd_set_line_width]]
* *cmd_set_line_width*(_cb_, [_linewidth_ = 1.0]) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetLineWidth.html[vkCmdSetLineWidth].#

[[cmd_set_line_stipple]]
* *cmd_set_line_stipple*(_cb_, _factor_, _pattern_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetLineStippleEXT.html[vkCmdSetLineStippleEXT].#

[[cmd_set_sample_locations]]
* *cmd_set_sample_locations*(_cb_, <<samplelocationsinfo, _samplelocationsinfo_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetSampleLocationsEXT.html[vkCmdSetSampleLocationsEXT].#

[[cmd_set_scissor]]
* *cmd_set_scissor*(_cb_, _first_, {<<rect2d, _rect2d_>>}) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetScissor.html[vkCmdSetScissor].#

[[cmd_set_stencil_compare_mask]]
* *cmd_set_stencil_compare_mask*(_cb_, _face_mask_, _compare_mask_) +
[small]#_face_mask_: <<stencilfaceflags, stencilfaceflags>> +
_compare_mask_: integer +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetStencilCompareMask.html[vkCmdSetStencilCompareMask].#

[[cmd_set_stencil_reference]]
* *cmd_set_stencil_reference*(_cb_, _face_mask_, _reference_) +
[small]#_face_mask_: <<stencilfaceflags, stencilfaceflags>> +
_reference_: integer +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetStencilReference.html[vkCmdSetStencilReference].#

[[cmd_set_stencil_write_mask]]
* *cmd_set_stencil_write_mask*(_cb_, _face_mask_, _write_mask_) +
[small]#_face_mask_: <<stencilfaceflags, stencilfaceflags>> +
_write_mask_: integer +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetStencilWriteMask.html[vkCmdSetStencilWriteMask].#

[[cmd_set_viewport]]
* *cmd_set_viewport*(_cb_, _first_, {<<viewport, _viewport_>>}) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetViewport.html[vkCmdSetViewport].#

[[cmd_update_buffer]]
* *cmd_update_buffer*(_cb_, _dst_buffer_, _dst_offset_, _data_) +
[small]#_dst_buffer_: <<buffer, buffer>> +
_dst_offset_: integer +
_data_: binary string (n x 4 bytes) +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdUpdateBuffer.html[vkCmdUpdateBuffer].#

[[cmd_wait_events]]
* *cmd_wait_events*(_cb_, _src_stage_mask_, _..._) +
[small]#arg2 - _src_stage_mask_: <<pipelinestageflags, pipelinestageflags>> +
arg3 - _dst_stage_mask_: <<pipelinestageflags, pipelinestageflags>> +
arg4 - _events_: {<<event, event>>} +
arg5 - [_memory_barriers_]: {<<memorybarrier, memorybarrier>>} +
arg6 - [_buffer_memory_barriers_]: {<<buffermemorybarrier, buffermemorybarrier>>} +
arg7 - [_image_memory_barriers_]: {<<imagememorybarrier, imagememorybarrier>>} +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdWaitEvents.html[vkCmdWaitEvents].#

[[cmd_write_timestamp]]
* *cmd_write_timestamp*(_cb_, <<pipelinestageflags, _pipelinestageflags_>>, <<query_pool, _query_pool_>>, _query_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdWriteTimestamp.html[vkCmdWriteTimestamp].#


