
[[constructors]]
=== Constructors

MoonVulkan <<structs, structs>> are plain Lua tables, and thus an instance of a struct is
usually created manually by simply creating a new table with the specified fields.

Alternatively, for a few struct types, a *table constructor* is provided and can be used
to save typing and reduce code verbosity. The constructor for a struct type, if available,
is a function of the *vk* table, having the same name of the struct type, and returning a
table initialized with the passed values.

Available constructors are listed just below the definitions of their respective types,
see for example the <<extent2d, extent2d>> type (notice that, for the sake of brevity, the
return value is not indicated).

Note that whenever a table constructor accepts a <<flags, flags>> parameter, this can
be passed either as integer code, or as a table of admitted literals for that flags type.

The following examples illustrate the use of constructors for the <<extent2d, extent2d>>
and  <<vk.imagesubresource, imagesubresource>> struct types:

.Examples
[source, lua, indent=1]
----
-- Two alternative ways to create an instance of the 'offset2d' type:
ext1 = { width=300, height=200 }   -- manually
ext2 = vk.extent2d(300, 200)       -- using the table constructor

-- Two alternative way of passing an 'imageaspectflags' parameter:
subres1 = vk.imagesubresource(vk.IMAGE_ASPECT_COLOR_BIT, 0, 0)  -- as an integer
subres2 = vk.imagesubresource({'color'}, 0, 0) -- as a table of admitted literals
----

