
[[debug_report_callback]]
==== debug_report_callback

The following functions require the 
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_EXT_debug_report[VK_EXT_debug_report] instance extension.


[[create_debug_report_callback]]
* _debug_report_callback_ = *create_debug_report_callback*(_instance_, _flags_, _func_ [, <<allocators, _allocatorLUD_>>]) +
[small]#_flags_: <<debugreportflags, debugreportflags>> +
The _func_ callback (a Lua function) will be executed as: +
*func(instance, flags, object_type, objectRAW, location, message_code, layer_prefix, message)*, +
where the parameters are the same as those for the <<debug_report_message, debug_report_message>>(&nbsp;) function. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkCreateDebugReportCallbackEXT[vkCreateDebugReportCallbackEXT].#

[[destroy_debug_report_callback]]
* *destroy_debug_report_callback*(_debug_report_callback_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkDestroyDebugReportCallbackEXT[vkDestroyDebugReportCallbackEXT].#

[[debug_report_message]]
* *debug_report_message*(_instance_, _flags_, _..._) +
[small]#arg2: _flags_: <<debugreportflags, debugreportflags>> +
arg3: _object_type_: <<debugreportobjecttype, debugreportobjecttype>> +
arg4: _objectRAW_: integer raw object handle (may be 0) +
arg5: _location_: integer +
arg6: _message_code_: integer +
arg7: _layer_prefix_: string +
arg8: _message_: string +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkDebugReportMessageEXT[vkDebugReportMessageEXT].#

[[debug_marker]]
==== Debug Marker

The following functions require the 
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_EXT_debug_marker[VK_EXT_debug_marker] device extension.

[[debug_marker_set_object_name]]
* *debug_marker_set_object_name*(_device_, _object_type_, _objectRAW_, _object_name_) +
[small]#_object_type_: <<debugreportobjecttype, debugreportobjecttype>> +
_objectRAW_: integer raw object handle (may be 0) +
_object_name_: string +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkDebugMarkerSetObjectNameEXT[vkDebugMarkerSetObjectNameEXT].#

[[debug_marker_set_object_tag]]
* *debug_marker_set_object_tag*(_device_, _object_type_, _objectRAW_, _tag_name_, _object_tag_) +
[small]#_object_type_: <<debugreportobjecttype, debugreportobjecttype>> +
_objectRAW_: integer raw object handle (may be 0) +
_tag_name_: integer +
_object_tag_: binary string +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkDebugMarkerSetObjectTagEXT[vkDebugMarkerSetObjectTagEXT].#

The functions that follow extend the list of <<commands, commands>>.

[[cmd_debug_marker_begin]]
* *cmd_debug_marker_begin*(_cb_, _marker_name_ [, _color_]) +
[small]#_marker_name_: string +
_color_: {float} (length = 4, opt.) +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkCmdDebugMarkerBeginEXT[vkCmdDebugMarkerBeginEXT].#

[[cmd_debug_marker_end]]
* *cmd_debug_marker_end*(_cb_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkCmdDebugMarkerEndEXT[vkCmdDebugMarkerEndEXT].#

[[cmd_debug_marker_insert]]
* *cmd_debug_marker_insert*(_cb_, _marker_name_ [, _color_]) +
[small]#_marker_name_: string +
_color_: {float} (length = 4, opt.) +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkCmdDebugMarkerInsertEXT[vkCmdDebugMarkerInsertEXT].#

////
[[]]
* <<,__>> = **(_xxx_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vk[].#

arg3 - __: integer +
arg3 - __: <<, >> +
arg3 - __: {<<, >>} +
arg3 - __: <<, >> (opt.) +
arg3 - __: {<<, >>} (opt.) +

////

