
[[device_memory]]
==== device_memory (_devmem_)

[[allocate_memory]]
* _devmem_ = *allocate_memory*(_device_, _allocation_size_, _memory_type_index_, [<<allocators, _allocator_>>], [_dedicated_]) +
[small]#_allocation_size_: integer +
_memory_type_index_: integer +
_dedicated_: <<image, _image_>> or <<buffer, _buffer_>> (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_dedicated_allocation[VK_KHR_dedicated_allocation] EXTENSION) +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkAllocateMemory[vkAllocateMemory].#

[[free_memory]]
* *free_memory*(_devmem_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkFreeMemory[vkFreeMemory].#

[[map_memory]]
* *map_memory*(_devmem_, _offset_, _size_, [_flags_]) +
[small]#_offset_: integer +
_size_: integer or '_whole size_' +
[_flags_]: <<memorymapflags, memorymapflags>> +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkMapMemory[vkMapMemory].#

[[unmap_memory]]
* *unmap_memory*(_devmem_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkUnmapMemory[vkUnmapMemory].#

[[write_memory]]
* *write_memory*(_devmem_, _offset_, _data_) +
[small]#_offset_: integer +
_data_: binary string.#

[[read_memory]]
* _data_ = *read_memory*(_devmem_, _offset_, _size_) +
[small]#_offset_: integer +
_size_: integer or '_whole size_' +
Returns _data_ as a binary string.#

[[get_device_memory_commitment]]
* _bytes_ = *get_device_memory_commitment*(_devmem_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkGetDeviceMemoryCommitment[vkGetDeviceMemoryCommitment].#

[[flush_mapped_memory_ranges]]
* *flush_mapped_memory_ranges*(_device_, _ranges_) +
[small]#_ranges_: {<<mappedmemoryrange, mappedmemoryrange>>} +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkFlushMappedMemoryRanges[vkFlushMappedMemoryRanges].#

[[invalidate_mapped_memory_ranges]]
* *invalidate_mapped_memory_ranges*(_device_, _ranges_) +
[small]#_ranges_: {<<mappedmemoryrange, mappedmemoryrange>>} +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkInvalidateMappedMemoryRanges[vkInvalidateMappedMemoryRanges].#

'''

NOTE: If the
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_get_memory_requirements2[VK_KHR_get_memory_requirements2]
device extension is enabled for the affected device,
then the functions it provides are used by the bindings described in this section.
Otherwise the original functions are used.


[[get_buffer_memory_requirements]]
* <<memoryrequirements, _memoryrequirements_>> = *get_buffer_memory_requirements*(<<buffer, _buffer_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkGetBufferMemoryRequirements[vkGetBufferMemoryRequirements] -
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkGetBufferMemoryRequirements2KHR[vkGetBufferMemoryRequirements2KHR].#

[[get_image_memory_requirements]]
* <<memoryrequirements, _memoryrequirements_>> = *get_image_memory_requirements*(<<image, _image_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkGetImageMemoryRequirements[vkGetImageMemoryRequirements] -
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkGetImageMemoryRequirements2KHR[vkGetImageMemoryRequirements2KHR].#

[[get_image_sparse_memory_requirements]]
* {<<sparseimagememoryrequirements, _sparseimagememoryrequirements_>>} = *get_image_sparse_memory_requirements*(<<image, _image_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkGetImageSparseMemoryRequirements[vkGetImageSparseMemoryRequirements] -
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkGetImageSparseMemoryRequirements2KHR[vkGetImageSparseMemoryRequirements2KHR].#

'''

[[bind_buffer_memory]]
* *bind_buffer_memory*(<<buffer, _buffer_>>, _devmem_, _offset_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkBindBufferMemory[vkBindBufferMemory].#

[[bind_image_memory]]
* *bind_image_memory*(<<image, _image_>>, _devmem_, _offset_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkBindImageMemory[vkBindImageMemory].#


