
[[flags]]
== Flags

Flags in MoonVulkan functions and structs are always represented as plain integers,
and encoded in the same way as the corresponding flags in the C Vulkan API.

The *vk* table contains the VK_XXX_BIT values, renamed as *vk.XXX_BIT*
(e.g. vk.STENCIL_FACE_FRONT_BIT, vk.STENCIL_FACE_BACK_BIT, etc.).

For each flags type (see the list below), a utility function is also available to map
an integer code to a list of string literals, each corresponding to an individual bit set 
in the code, and viceversa to encode an integer value from the individual bits given 
as a list of string literals. 
The generic definition of such functions is the following, where *xxxflags* stands for 
*stencilfaceflags*, *commandbufferresetflags*, etc:

[[xxxflags]]
* _code_ = *xxxflags*(_s1_, _s2_, _..._) +
_s1_, _s2_, _..._ = *xxxflags*(_code_) +
[small]#Maps the integer _code_ to/from the list of string values _s1_, _s2_, _..._.#

See also the <<flags_snippet, example>> contained in the code snippets section.


[[accessflags]]
[small]#*accessflags*: vk.ACCESS_XXX_BIT +
Values: 
'_indirect command read_', '_index read_', '_vertex attribute read_', '_uniform read_', '_input attachment read_', '_shader read_', '_shader write_', '_color attachment read_', '_color attachment write_', '_depth stencil attachment read_', '_depth stencil attachment write_', '_transfer read_', '_transfer write_', '_host read_', '_host write_', '_memory read_', '_memory write_', '_color attachment read noncoherent_', '_conditional rendering read_', '_transform feedback write_, '_transform feedback counter read_, '_transform feedback counter write_', '_fragment density map read_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkAccessFlagBits.html[VkAccessFlagBits].#

[[attachmentdescriptionflags]]
[small]#*attachmentdescriptionflags*: vk.ATTACHMENT_DESCRIPTION_XXX_BIT +
Values: 
'_may alias_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkAttachmentDescriptionFlagBits.html[VkAttachmentDescriptionFlagBits].#

[[buffercreateflags]]
[small]#*buffercreateflags*: vk.BUFFER_CREATE_XXX_BIT +
Values: 
'_sparse binding_', '_sparse residency_', '_sparse aliased_', '_protected_', '_device address capture replay_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkBufferCreateFlagBits.html[VkBufferCreateFlagBits].#

[[bufferusageflags]]
[small]#*bufferusageflags*: vk.BUFFER_USAGE_XXX_BIT +
Values: 
'_transfer src_', '_transfer dst_', '_uniform texel buffer_', '_storage texel buffer_', '_uniform buffer_', '_storage buffer_', '_index buffer_', '_vertex buffer_', '_indirect buffer_', '_conditional rendering_', '_transform feedback buffer_', '_transform feedback counter buffer_', '_shader device address_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkBufferUsageFlagBits.html[VkBufferUsageFlagBits].#

[[colorcomponentflags]]
[small]#*colorcomponentflags*: vk.COLOR_COMPONENT_XXX_BIT +
Values: 
'_r_', '_g_', '_b_', '_a_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkColorComponentFlagBits.html[VkColorComponentFlagBits].#

[[commandbufferresetflags]]
[small]#*commandbufferresetflags*: vk.COMMAND_BUFFER_RESET_XXX_BIT +
Values: 
'_release resources_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkCommandBufferResetFlagBits.html[VkCommandBufferResetFlagBits].#

[[commandbufferusageflags]]
[small]#*commandbufferusageflags*: vk.COMMAND_BUFFER_USAGE_XXX_BIT +
Values: 
'_one time submit_', '_render pass continue_', '_simultaneous use_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkCommandBufferUsageFlagBits.html[VkCommandBufferUsageFlagBits].#

[[commandpoolcreateflags]]
[small]#*commandpoolcreateflags*: vk.COMMAND_POOL_CREATE_XXX_BIT +
Values: 
'_transient_', '_reset command buffer_', '_protected_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkCommandPoolCreateFlagBits.html[VkCommandPoolCreateFlagBits].#

[[commandpoolresetflags]]
[small]#*commandpoolresetflags*: vk.COMMAND_POOL_RESET_XXX_BIT +
Values: 
'_release resources_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkCommandPoolResetFlagBits.html[VkCommandPoolResetFlagBits].#

[[compositealphaflags]]
[small]#*compositealphaflags*: vk.COMPOSITE_ALPHA_XXX_BIT_KHR +
Values: 
'_opaque_', '_pre multiplied_', '_post multiplied_', '_inherit_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkCompositeAlphaFlagBitsKHR.html[VkCompositeAlphaFlagBitsKHR].#

[[conditionalrenderingflags]]
[small]#*conditionalrenderingflags*: vk.CONDITIONAL_RENDERING_XXX_BIT_EXT +
Values: '_inverted_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkConditionalRenderingFlagBitsEXT.html[VkConditionalRenderingFlagBitsEXT].#

[[cullmodeflags]]
[small]#*cullmodeflags*: vk.CULL_MODE_XXX +
Values: 
'_none_' (=0), '_front_', '_back_', '_front and back_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkCullModeFlagBits.html[VkCullModeFlagBits].#

[[debugreportflags]]
[small]#*debugreportflags*: vk.DEBUG_REPORT_XXX_BIT_EXT +
Values: 
'_information_', '_warning_', '_performance warning_', '_report_', '_debug_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDebugReportFlagBitsEXT.html[VkDebugReportFlagBitsEXT].#

[[debugutilsmessageseverityflags]]
[small]#*debugutilsmessageseverityflags*: vk.DEBUG_UTILS_MESSAGE_SEVERITY_XXX_BIT_EXT +
Values: '_verbose_', '_info_', '_warning_', '_error_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDebugUtilsMessageSeverityFlagBitsEXT.html[VkDebugUtilsMessageSeverityFlagBitsEXT].#

[[debugutilsmessagetypeflags]]
[small]#*debugutilsmessagetypeflags*: vk.DEBUG_UTILS_MESSAGE_TYPE_XXX_BIT_EXT +
Values: '_general_', '_validation_', '_performance_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDebugUtilsMessageTypeFlagBitsEXT.html[VkDebugUtilsMessageTypeFlagBitsEXT].#

[[dependencyflags]]
[small]#*dependencyflags*: vk.DEPENDENCY_XXX_BIT +
Values: 
'_by region_', '_device group_', '_view local_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDependencyFlagBits.html[VkDependencyFlagBits].#

[[descriptorbindingflags]]
[small]#*descriptorbindingflags*: vk.DESCRIPTOR_BINDING_XXX_BIT_EXT +
Values:
'_update after bind_', '_update unused while pending_', '_partially bound_', '_variable descriptor count_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDescriptorBindingFlagBitsEXT.html[VkDescriptorBindingFlagBitsEXT].#

[[descriptorpoolcreateflags]]
[small]#*descriptorpoolcreateflags*: vk.DESCRIPTOR_POOL_CREATE_XXX_BIT +
Values: 
'_free descriptor set_', '_update after bind_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDescriptorPoolCreateFlagBits.html[VkDescriptorPoolCreateFlagBits].#

[[descriptorsetlayoutcreateflags]]
[small]#*descriptorsetlayoutcreateflags*: vk.DESCRIPTOR_SET_LAYOUT_CREATE_XXX_BIT +
Values: 
'_push descriptor_', '_update after bind pool_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDescriptorSetLayoutCreateFlagBits.html[VkDescriptorSetLayoutCreateFlagBits].#

[[devicegrouppresentmodeflags]]
[small]#*devicegrouppresentmodeflags*: vk.DEVICE_GROUP_PRESENT_MODE_XXX_BIT_KHR +
Values: '_local_', '_remote_', '_sum_', '_local multi device_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDeviceGroupPresentModeFlagBitsKHR.html[VkDeviceGroupPresentModeFlagBitsKHR].#

[[devicequeuecreateflags]]
[small]#*devicequeuecreateflags*: vk.DEVICE_QUEUE_CREATE_XXX_BIT +
Values: '_protected_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDeviceQueueCreateFlagBits.html[VkDeviceQueueCreateFlagBits].#

[[displayplanealphaflags]]
[small]#*displayplanealphaflags*: vk.DISPLAY_PLANE_ALPHA_XXX_BIT_KHR +
Values: '_opaque_', '_global_', '_per pixel_', '_per pixel premultiplied_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDisplayPlaneAlphaFlagBitsKHR.html[VkDisplayPlaneAlphaFlagBitsKHR].#

[[externalfencefeatureflags]]
[small]#*externalfencefeatureflags*: vk.EXTERNAL_FENCE_FEATURE_XXX_BIT +
Values: '_exportable_', '_importable_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkExternalFenceFeatureFlagBits.html[VkExternalFenceFeatureFlagBits].#

[[externalfencehandletypeflags]]
[small]#*externalfencehandletypeflags*: vk.EXTERNAL_FENCE_HANDLE_TYPE_XXX_BIT +
Values: '_opaque_fd_', '_opaque_win32_', '_opaque_win32_kmt_', '_sync_fd_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkExternalFenceHandleTypeFlagBits.html[VkExternalFenceHandleTypeFlagBits].#

[[externalmemoryfeatureflags]]
[small]#*externalmemoryfeatureflags*: vk.EXTERNAL_MEMORY_FEATURE_XXX_BIT +
Values: '_dedicated only_', '_exportable_', '_importable_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkExternalMemoryFeatureFlagBits.html[VkExternalMemoryFeatureFlagBits].#

[[externalmemoryhandletypeflags]]
[small]#*externalmemoryhandletypeflags*: vk.EXTERNAL_MEMORY_HANDLE_TYPE_XXX_BIT +
Values: '_opaque fd_', '_opaque win32_', '_opaque win32 kmt_', '_d3d11 texture_', '_d3d11 texture kmt_', '_d3d12 heap_', '_d3d12 resource_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkExternalMemoryHandleTypeFlagBits.html[VkExternalMemoryHandleTypeFlagBits].#

[[externalsemaphorefeatureflags]]
[small]#*externalsemaphorefeatureflags*: vk.EXTERNAL_SEMAPHORE_FEATURE_XXX_BIT +
Values: '_exportable_', '_importable_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkExternalSemaphoreFeatureFlagBits.html[VkExternalSemaphoreFeatureFlagBits].#

[[externalsemaphorehandletypeflags]]
[small]#*externalsemaphorehandletypeflags*: vk.EXTERNAL_SEMAPHORE_HANDLE_TYPE_XXX_BIT +
Values: '_opaque fd_', '_opaque win32_', '_opaque win32 kmt_', '_d3d12 fence_', '_sync fd_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkExternalSemaphoreHandleTypeFlagBits.html[VkExternalSemaphoreHandleTypeFlagBits].#

[[fencecreateflags]]
[small]#*fencecreateflags*: vk.FENCE_CREATE_XXX_BIT +
Values: 
'_signaled_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkFenceCreateFlagBits.html[VkFenceCreateFlagBits].#

[[fenceimportflags]]
[small]#*fenceimportflags*: vk.FENCE_IMPORT_XXX_BIT +
Values: '_temporary_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkFenceImportFlagBits.html[VkFenceImportFlagBits].#

[[formatfeatureflags]]
[small]#*formatfeatureflags*: vk.FORMAT_FEATURE_XXX_BIT +
Values: 
'_sampled image_', '_storage image_', '_storage image atomic_', '_uniform texel buffer_', '_storage texel buffer_', '_storage texel buffer atomic_', '_vertex buffer_', '_color attachment_', '_color attachment blend_', '_depth stencil attachment_', '_blit src_', '_blit dst_', '_transfer src_', '_transfer dst_', '_sampled image filter linear_', '_sampled image filter minmax_', '_midpoint chroma samples_', '_sampled image ycbcr conversion linear filter_', '_sampled image ycbcr conversion separate reconstruction filter_', '_sampled image ycbcr conversion chroma reconstruction explicit_', '_sampled image ycbcr conversion chroma reconstruction explicit forceable_', '_disjoint_', '_cosited chroma samples_', '_fragment density map_', '_sampled image filter cubic_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkFormatFeatureFlagBits.html[VkFormatFeatureFlagBits].#

[[framebuffercreateflags]]
[small]#*framebuffercreateflags*: vk.FRAMEBUFFER_CREATE_XXX_BIT +
Values: '_imageless_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkFramebufferCreateFlagBits.html[VkFramebufferCreateFlagBits].#

[[imageaspectflags]]
[small]#*imageaspectflags*: vk.IMAGE_ASPECT_XXX_BIT +
Values: 
'_color_', '_depth_', '_stencil_', '_metadata_', '_plane 0_', '_plane 1_', '_plane 2_', '_memory plane 0_', '_memory plane 1_', '_memory plane 2_', '_memory plane 3_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkImageAspectFlagBits.html[VkImageAspectFlagBits].#

[[imagecreateflags]]
[small]#*imagecreateflags*: vk.IMAGE_CREATE_XXX_BIT +
Values: 
'_sparse binding_', '_sparse residency_', '_sparse aliased_', '_mutable format_', '_cube compatible_', '_block texel view compatible_', '_extended usage_', '_sample locations compatible depth_', '_disjoint_', '_alias_','_split instance bind regions_', '_2d array compatible_', '_protected_', '_subsampled_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkImageCreateFlagBits.html[VkImageCreateFlagBits].#

[[imageusageflags]]
[small]#*imageusageflags*: vk.IMAGE_USAGE_XXX_BIT +
Values: 
'_transfer src_', '_transfer dst_', '_sampled_', '_storage_', '_color attachment_', '_depth stencil attachment_', '_transient attachment_', '_input attachment_', '_fragment density map_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkImageUsageFlagBits.html[VkImageUsageFlagBits].#

[[imageviewcreateflags]]
[small]#*imageviewcreateflags*: vk.IMAGE_VIEW_CREATE_XXX_BIT +
Values: '_fragment density map dynamic_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkImageViewCreateFlagBits.html[VkImageViewCreateFlagBits].#

[[memoryallocateflags]]
[small]#*memoryallocateflags*: vk.MEMORY_ALLOCATE_XXX_BIT +
Values: '_device mask_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkMemoryAllocateFlagBits.html[VkMemoryAllocateFlagBits].#

[[memoryheapflags]]
[small]#*memoryheapflags*: vk.MEMORY_HEAP_XXX_BIT +
Values: 
'_device local_', '_multi instance_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkMemoryHeapFlagBits.html[VkMemoryHeapFlagBits].#

[[memorypropertyflags]]
[small]#*memorypropertyflags*: vk.MEMORY_PROPERTY_XXX_BIT +
Values: 
'_device local_', '_host visible_', '_host coherent_', '_host cached_', '_lazily allocated_', '_protected_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkMemoryPropertyFlagBits.html[VkMemoryPropertyFlagBits].#

[[peermemoryfeatureflags]]
[small]#*peermemoryfeatureflags*: vk.PEER_MEMORY_FEATURE_XXX_BIT +
Values: '_copy src_', '_copy dst_', '_generic src_', '_generic dst_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPeerMemoryFeatureFlagBits.html[VkPeerMemoryFeatureFlagBits].#

[[pipelinecreateflags]]
[small]#*pipelinecreateflags*: vk.PIPELINE_CREATE_XXX_BIT +
Values: 
'_disable optimization_', '_allow derivatives_', '_derivative_', '_view index from device index_', '_dispatch base_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPipelineCreateFlagBits.html[VkPipelineCreateFlagBits].#

[[pipelinecreationfeedbackflags]]
[small]#*pipelinecreationfeedbackflags*: vk.PIPELINE_CREATION_FEEDBACK_XXX_BIT_EXT +
Values:'_valid_', '_application pipeline cache hit_', '_base pipeline acceleration_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPipelineCreationFeedbackFlagBitsEXT.html[VkPipelineCreationFeedbackFlagBitsEXT].#

[[pipelinestageflags]]
[small]#*pipelinestageflags*: vk.PIPELINE_STAGE_XXX_BIT +
Values: 
'_top of pipe_', '_draw indirect_', '_vertex input_', '_vertex shader_', '_tessellation control shader_', '_tessellation evaluation shader_', '_geometry shader_', '_fragment shader_', '_early fragment tests_', '_late fragment tests_', '_color attachment output_', '_compute shader_', '_transfer_', '_bottom of pipe_', '_host_', '_all graphics_', '_all commands_', '_conditional rendering_', '_transform feedback_', '_fragment density process_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPipelineStageFlagBits.html[VkPipelineStageFlagBits].#

[[querycontrolflags]]
[small]#*querycontrolflags*: vk.QUERY_CONTROL_XXX_BIT +
Values: 
'_precise_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkQueryControlFlagBits.html[VkQueryControlFlagBits].#

[[querypipelinestatisticflags]]
[small]#*querypipelinestatisticflags*: vk.QUERY_PIPELINE_STATISTIC_XXX_BIT +
Values: 
'_input assembly vertices_', '_input assembly primitives_', '_vertex shader invocations_', '_geometry shader invocations_', '_geometry shader primitives_', '_clipping invocations_', '_clipping primitives_', '_fragment shader invocations_', '_tessellation control shader patches_', '_tessellation evaluation shader invocations_', '_compute shader invocations_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkQueryPipelineStatisticFlagBits.html[VkQueryPipelineStatisticFlagBits].#

[[queryresultflags]]
[small]#*queryresultflags*: vk.QUERY_RESULT_XXX_BIT +
Values: 
'_64_', '_wait_', '_with availability_', '_partial_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkQueryResultFlagBits.html[VkQueryResultFlagBits].#

[[queueflags]]
[small]#*queueflags*: vk.QUEUE_XXX_BIT +
Values: 
'_graphics_', '_compute_', '_transfer_', '_sparse binding_', '_protected_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkQueueFlagBits.html[VkQueueFlagBits].#

[[resolvemodeflags]]
[small]#*resolvemodeflags*: vk.RESOLVE_MODE_XXX_BIT_KHR +
Values: '_none_','_sample zero_','_average_','_min_','_max_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkResolveModeFlagBitsKHR.html[VkResolveModeFlagBitsKHR].#

[[samplecountflags]]
[small]#*samplecountflags*: vk.SAMPLE_COUNT_XXX_BIT +
Values: 
'_1_', '_2_', '_4_', '_8_', '_16_', '_32_', '_64_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkSampleCountFlagBits.html[VkSampleCountFlagBits].#

[[samplercreateflags]]
[small]#*samplercreateflags*: vk.SAMPLER_CREATE_XXX_BIT +
Values: '_subsampled_', '_subsampled coarse reconstruction_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkSamplerCreateFlagBits.html[VkSamplerCreateFlagBits].#


[[semaphoreimportflags]]
[small]#*semaphoreimportflags*: vk.SEMAPHORE_IMPORT_XXX_BIT +
Values: '_temporary_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkSemaphoreImportFlagBits.html[VkSemaphoreImportFlagBits].#

[[shaderstageflags]]
[small]#*shaderstageflags*: vk.SHADER_STAGE_XXX_BIT +
Values: 
'_vertex_', '_tessellation control_', '_tessellation evaluation_', '_geometry_', '_fragment_', '_compute_', '_all graphics_', '_all_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkShaderStageFlagBits.html[VkShaderStageFlagBits].#

[[sparseimageformatflags]]
[small]#*sparseimageformatflags*: vk.SPARSE_IMAGE_FORMAT_XXX_BIT +
Values: 
'_single miptail_', '_aligned mip size_', '_nonstandard block size_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkSparseImageFormatFlagBits.html[VkSparseImageFormatFlagBits].#

[[sparsememorybindflags]]
[small]#*sparsememorybindflags*: vk.SPARSE_MEMORY_BIND_XXX_BIT +
Values: 
'_metadata_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkSparseMemoryBindFlagBits.html[VkSparseMemoryBindFlagBits].#

[[stencilfaceflags]]
[small]#*stencilfaceflags*: vk.STENCIL_FACE_XXX_BIT +
Values: 
'_front_', '_back_'. +
Rfr. https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkStencilFaceFlagBits.html[VkStencilFaceFlagBits].#

[[subgroupfeatureflags]]
[small]#*subgroupfeatureflags*: vk.SUBGROUP_FEATURE_XXX_BIT +
Values: '_basic_', '_vote_', '_arithmetic_', '_ballot_', '_shuffle_', '_shuffle relative_', '_clustered_', '_quad_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkSubgroupFeatureFlagBits.html[VkSubgroupFeatureFlagBits].#

[[surfacecounterflags]]
[small]#*surfacecounterflags*: vk.SURFACE_COUNTER_XXX_BIT_EXT +
Values: '_vblank_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkSurfaceCounterFlagBitsEXT.html[VkSurfaceCounterFlagBitsEXT].#

[[surfacetransformflags]]
[small]#*surfacetransformflags*: vk.SURFACE_TRANSFORM_XXX_BIT_KHR +
Values: 
'_identity_', '_rotate 90_', '_rotate 180_', '_rotate 270_', '_horizontal mirror_', '_horizontal mirror rotate 90_', '_horizontal mirror rotate 180_', '_horizontal mirror rotate 270_', '_inherit_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkSurfaceTransformFlagBitsKHR.html[VkSurfaceTransformFlagBitsKHR].#

[[swapchaincreateflags]]
[small]#*swapchaincreateflags*: vk.SWAPCHAIN_CREATE_XXX_BIT_KHR +
Values: '_split instance bind regions_', '_protected_', '_mutable format_'. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkSwapchainCreateFlagBitsKHR.html[VkSwapchainCreateFlagBitsKHR].#

Reserved for future use (must be set to 0):

[[bufferviewcreateflags]]
[small]#*bufferviewcreateflags*: 0#

[[commandpooltrimflags]]
[small]#*commandpooltrimflags*: 0#

[[debugutilsmessengercallbackdataflags]]
[small]#*debugutilsmessengercallbackdataflags*: 0#

[[debugutilsmessengercreateflags]]
[small]#*debugutilsmessengercreateflags*: 0#

[[descriptorpoolresetflags]]
[small]#*descriptorpoolresetflags*: 0#

[[descriptorupdatetemplatecreateflags]]
[small]#*descriptorupdatetemplatecreateflags*: 0#

[[devicecreateflags]]
[small]#*devicecreateflags*: 0#

[[displaymodecreateflags]]
[small]#*displaymodecreateflags*: 0#

[[displaysurfacecreateflags]]
[small]#*displaysurfacecreateflags*: 0#

[[eventcreateflags]]
[small]#*eventcreateflags*: 0#

[[instancecreateflags]]
[small]#*instancecreateflags*: 0#

[[memorymapflags]]
[small]#*memorymapflags*: 0#

[[pipelinecachecreateflags]]
[small]#*pipelinecachecreateflags*: 0#

[[pipelinecolorblendstatecreateflags]]
[small]#*pipelinecolorblendstatecreateflags*: 0#

[[pipelinerasterizationconservativestatecreateflags]]
[small]#*pipelinerasterizationconservativestatecreateflags*: 0#

[[pipelinerasterizationstatestreamcreateflags]]
[small]#*pipelinerasterizationstatestreamcreateflags*: 0#

[[pipelinedepthstencilstatecreateflags]]
[small]#*pipelinedepthstencilstatecreateflags*: 0#

[[pipelinediscardrectanglestatecreateflags]]
[small]#*pipelinediscardrectanglestatecreateflags*: 0#

[[pipelinedynamicstatecreateflags]]
[small]#*pipelinedynamicstatecreateflags*: 0#

[[pipelineinputassemblystatecreateflags]]
[small]#*pipelineinputassemblystatecreateflags*: 0#

[[pipelinelayoutcreateflags]]
[small]#*pipelinelayoutcreateflags*: 0#

[[pipelinemultisamplestatecreateflags]]
[small]#*pipelinemultisamplestatecreateflags*: 0#

[[pipelinerasterizationstatecreateflags]]
[small]#*pipelinerasterizationstatecreateflags*: 0#

[[pipelineshaderstagecreateflags]]
[small]#*pipelineshaderstagecreateflags*: 0#

[[pipelinetessellationstatecreateflags]]
[small]#*pipelinetessellationstatecreateflags*: 0#

[[pipelinevertexinputstatecreateflags]]
[small]#*pipelinevertexinputstatecreateflags*: 0#

[[pipelineviewportstatecreateflags]]
[small]#*pipelineviewportstatecreateflags*: 0#

[[querypoolcreateflags]]
[small]#*querypoolcreateflags*: 0#

[[renderpasscreateflags]]
[small]#*renderpasscreateflags*: 0#

[[semaphorecreateflags]]
[small]#*semaphorecreateflags*: 0#

[[shadermodulecreateflags]]
[small]#*shadermodulecreateflags*: 0#

[[subpassdescriptionflags]]
[small]#*subpassdescriptionflags*: 0#

[[validationcachecreateflags]]
[small]#*validationcachecreateflags*: 0#

////
[[flags]]
[small]#**: 0#

[[zzzflags]]
[small]#*zzzflags*: vk.ZZZ_XXX_BIT_KHR +
Values: 
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkZzzFlagBits.html[VkZzzFlagBits].#

////

