
[[physical_device]]
==== physical_device

In this document, _physdev_ is an abbreviation for _physical_device_ when referring to a variable
or a return value.

[[enumerate_physical_devices]]
* {_physdev_} = *enumerate_physical_devices*(<<instance, _instance_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#vkEnumeratePhysicalDevices[vkEnumeratePhysicalDevices].#

////
NOTE: If the
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_get_physical_device_properties2[VK_KHR_get_physical_device_properties2] 
instance extension is enabled for the affected _physdev_,
then the functions it provides are used by the bindings described in this section.
////

[[get_physical_device_properties]]
* <<physicaldeviceproperties,_physicaldeviceproperties_>> = *get_physical_device_properties*(_physdev_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#vkGetPhysicalDeviceProperties[vkGetPhysicalDeviceProperties].#

[[get_physical_device_features]]
* <<physicaldevicefeatures,_physicaldevicefeatures_>> = *get_physical_device_features*(_physdev_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#vkGetPhysicalDeviceFeatures[vkGetPhysicalDeviceFeatures].#

[[get_physical_device_queue_family_properties]]
* {<<queuefamilyproperties,_queuefamilyproperties_>>} = *get_physical_device_queue_family_properties*(_physdev_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#vkGetPhysicalDeviceQueueFamilyProperties[vkGetPhysicalDeviceQueueFamilyProperties].#

[[get_physical_device_memory_properties]]
* <<physicaldevicememoryproperties,_physicaldevicememoryproperties_>> = *get_physical_device_memory_properties*(_physdev_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#vkGetPhysicalDeviceMemoryProperties[vkGetPhysicalDeviceMemoryProperties].#

[[get_physical_device_format_properties]]
* <<formatproperties,_formatproperties_>> = *get_physical_device_format_properties*(_physdev_, <<format,_format_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#vkGetPhysicalDeviceFormatProperties[vkGetPhysicalDeviceFormatProperties].#

[[get_physical_device_image_format_properties]]
* <<imageformatproperties,_imageformatproperties_>> = *get_physical_device_image_format_properties*(_physdev_, _info_) +
[small]#_info_: <<physicaldeviceimageformatinfo, physicaldeviceimageformatinfo>>. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#vkGetPhysicalDeviceImageFormatProperties[vkGetPhysicalDeviceImageFormatProperties].#

[[get_physical_device_sparse_image_format_properties]]
* <<sparseimageformatproperties,_sparseimageformatproperties_>> = *get_physical_device_sparse_image_format_properties*(_physdev_, _info_) +
[small]#_info_: <<physicaldevicesparseimageformatinfo, physicaldevicesparseimageformatinfo>>. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#vkGetPhysicalDeviceSparseImageFormatProperties[vkGetPhysicalDeviceSparseImageFormatProperties].#

[[get_physical_device_external_buffer_properties]]
* <<externalbufferproperties,_externalbufferproperties_>> = *get_physical_device_external_buffer_properties*(_physdev_, _info_) +
[small]#_info_: <<physicaldeviceexternalbufferinfo, physicaldeviceexternalbufferinfo>>. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#vkGetPhysicalDeviceExternalBufferPropertiesKHR[vkGetPhysicalDeviceExternalBufferPropertiesKHR] (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_external_memory_capabilities[VK_KHR_external_memory_capabilities] extension).#

[[get_physical_device_external_fence_properties]]
* <<externalfenceproperties,_externalfenceproperties_>> = *get_physical_device_external_fence_properties*(_physdev_, _info_) +
[small]#_info_: <<physicaldeviceexternalfenceinfo, physicaldeviceexternalfenceinfo>>. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#vkGetPhysicalDeviceExternalFencePropertiesKHR[vkGetPhysicalDeviceExternalFencePropertiesKHR] (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_external_fence_capabilities[VK_KHR_external_fence_capabilities] extension).#

[[get_physical_device_external_semaphore_properties]]
* <<externalsemaphoreproperties,_externalsemaphoreproperties_>> = *get_physical_device_external_semaphore_properties*(_physdev_, _info_) +
[small]#_info_: <<physicaldeviceexternalsemaphoreinfo, physicaldeviceexternalsemaphoreinfo>>. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#vkGetPhysicalDeviceExternalSemaphorePropertiesKHR[vkGetPhysicalDeviceExternalSemaphorePropertiesKHR] (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_external_semaphore_capabilities[VK_KHR_external_semaphore_capabilities] extension).#

[[get_physical_device_multisample_properties]]
* <<multisampleproperties,_multisampleproperties_>> = *get_physical_device_multisample_properties*(_physdev_, <<samplecountflags, _samplecountflags_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#vkGetPhysicalDeviceMultisamplePropertiesEXT[vkGetPhysicalDeviceMultisamplePropertiesEXT] (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_EXT_sample_locations[VK_EXT_sample_locations] extension).#

