
[[physical_device]]
==== physical_device

In this document, _physdev_ is an abbreviation for _physical_device_ when referring to a variable
or a return value.

[[enumerate_physical_devices]]
* {_physdev_} = *enumerate_physical_devices*(<<instance, _instance_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkEnumeratePhysicalDevices.html[vkEnumeratePhysicalDevices].#

[[enumerate_physical_device_groups]]
* {<<physicaldevicegroupproperties, _physicaldevicegroupproperties_>>} = *enumerate_physical_device_groups*(<<instance, _instance_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkEnumeratePhysicalDeviceGroups.html[vkEnumeratePhysicalDeviceGroups].#

[[get_physical_device_properties]]
* <<physicaldeviceproperties,_physicaldeviceproperties_>> = *get_physical_device_properties*(_physdev_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceProperties.html[vkGetPhysicalDeviceProperties], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceProperties2.html[vkGetPhysicalDeviceProperties2].#

[[get_physical_device_features]]
* <<physicaldevicefeatures,_physicaldevicefeatures_>> = *get_physical_device_features*(_physdev_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceFeatures.html[vkGetPhysicalDeviceFeatures], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceFeatures2.html[vkGetPhysicalDeviceFeatures2].#

[[get_physical_device_queue_family_properties]]
* {<<queuefamilyproperties,_queuefamilyproperties_>>} = *get_physical_device_queue_family_properties*(_physdev_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceQueueFamilyProperties.html[vkGetPhysicalDeviceQueueFamilyProperties], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceQueueFamilyProperties2.html[vkGetPhysicalDeviceQueueFamilyProperties2].#

[[get_physical_device_memory_properties]]
* <<physicaldevicememoryproperties,_physicaldevicememoryproperties_>> = *get_physical_device_memory_properties*(_physdev_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceMemoryProperties.html[vkGetPhysicalDeviceMemoryProperties], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceMemoryProperties2.html[vkGetPhysicalDeviceMemoryProperties2].#

[[get_physical_device_format_properties]]
* <<formatproperties,_formatproperties_>> = *get_physical_device_format_properties*(_physdev_, <<format,_format_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceFormatProperties.html[vkGetPhysicalDeviceFormatProperties], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceFormatProperties2.html[vkGetPhysicalDeviceFormatProperties2].#

[[get_physical_device_image_format_properties]]
* <<imageformatproperties,_imageformatproperties_>> = *get_physical_device_image_format_properties*(_physdev_, _info_) +
[small]#_info_: <<physicaldeviceimageformatinfo, physicaldeviceimageformatinfo>>. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceImageFormatProperties.html[vkGetPhysicalDeviceImageFormatProperties], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceImageFormatProperties2.html[vkGetPhysicalDeviceImageFormatProperties2].#

[[get_physical_device_sparse_image_format_properties]]
* <<sparseimageformatproperties,_sparseimageformatproperties_>> = *get_physical_device_sparse_image_format_properties*(_physdev_, _info_) +
[small]#_info_: <<physicaldevicesparseimageformatinfo, physicaldevicesparseimageformatinfo>>. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceSparseImageFormatProperties.html[vkGetPhysicalDeviceSparseImageFormatProperties], https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceSparseImageFormatProperties2.html[vkGetPhysicalDeviceSparseImageFormatProperties2].#

[[get_physical_device_external_buffer_properties]]
* <<externalbufferproperties,_externalbufferproperties_>> = *get_physical_device_external_buffer_properties*(_physdev_, _info_) +
[small]#_info_: <<physicaldeviceexternalbufferinfo, physicaldeviceexternalbufferinfo>>. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceExternalBufferProperties.html[vkGetPhysicalDeviceExternalBufferProperties].#

[[get_physical_device_external_fence_properties]]
* <<externalfenceproperties,_externalfenceproperties_>> = *get_physical_device_external_fence_properties*(_physdev_, _info_) +
[small]#_info_: <<physicaldeviceexternalfenceinfo, physicaldeviceexternalfenceinfo>>. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceExternalFenceProperties.html[vkGetPhysicalDeviceExternalFenceProperties].#

[[get_physical_device_external_semaphore_properties]]
* <<externalsemaphoreproperties,_externalsemaphoreproperties_>> = *get_physical_device_external_semaphore_properties*(_physdev_, _info_) +
[small]#_info_: <<physicaldeviceexternalsemaphoreinfo, physicaldeviceexternalsemaphoreinfo>>. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceExternalSemaphoreProperties.html[vkGetPhysicalDeviceExternalSemaphoreProperties].#

[[get_physical_device_multisample_properties]]
* <<multisampleproperties,_multisampleproperties_>> = *get_physical_device_multisample_properties*(_physdev_, <<samplecountflags, _samplecountflags_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceMultisamplePropertiesEXT.html[vkGetPhysicalDeviceMultisamplePropertiesEXT].#

[[get_physical_device_calibrateable_time_domains]]
* {<<timedomain, _timedomain_>>} = *get_physical_device_calibrateable_time_domains*(_physdev_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceCalibrateableTimeDomainsEXT.html[vkGetPhysicalDeviceCalibrateableTimeDomainsEXT].#

[[get_physical_device_fragment_shading_rates]]
* {<<physicaldevicefragmentshadingrate, _physicaldevicefragmentshadingrate_>>} = *get_physical_device_fragment_shading_rates*(_physdev_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceFragmentShadingRatesKHR.html[vkGetPhysicalDeviceFragmentShadingRatesKHR].#

[[get_physical_device_tool_properties]]
* {<<physicaldevicetoolproperties, _physicaldevicetoolproperties_>>} = *get_physical_device_tool_properties*(_physdev_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceToolPropertiesEXT.html[vkGetPhysicalDeviceToolPropertiesEXT].#

[[enumerate_physical_device_queue_family_performance_query_counters]]
* {<<performancecounter, _performancecounter_>>}, {<<performancecounterdescription, _performancecounterdescription_>>} = *enumerate_physical_device_queue_family_performance_query_counters*(_physdev_, _queue_family_index_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR.html[vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR].#

[[get_physical_device_queue_family_performance_query_passes]]
* _num_passes_ = *get_physical_device_queue_family_performance_query_passes*(_physdev_, <<querypoolperformancecreateinfo, _querypoolperformancecreateinfo_>>) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR.html[vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR].#
