
[[platform_surfaces]]
===== Platform-specific surface API

Platform-specific surface API are available only if MoonVulkan was <<platform_support, compiled with support enabled for the desired platforms>>.

Note, however, that the platform-specific functions described in this section are not needed if
surfaces are created using MoonGLFW or equivalent libraries that handle platform-specific details.

(Hint: Use MoonGLFW, avoid compiling for specific platforms, and ignore this section).

'''

[[get_physical_device_xlib_presentation_support]]
* _boolean_ = *get_physical_device_xlib_presentation_support*(_physdev_, _familyindex_, _display_, _visual_id_) +
[small]#_display_: lightuserdata +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkGetPhysicalDeviceXlibPresentationSupportKHR[vkGetPhysicalDeviceXlibPresentationSupportKHR] (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_xlib_surface[VK_KHR_xlib_surface] extension).#

[[create_xlib_surface]]
* _surface_ = *create_xlib_surface*(_instance_, _flags_, _display_, _window_, [<<allocators, _allocator_>>]) +
[small]#_display_: lightuserdata +
_window_: lightuserdata +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkCreateXlibSurfaceKHR[vkCreateXlibSurfaceKHR] (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_xlib_surface[VK_KHR_xlib_surface] extension).#

'''

[[get_physical_device_xcb_presentation_support]]
* _boolean_ = *get_physical_device_xcb_presentation_support*(_physdev_, _familyindex_, _connection_, _visual_id_) +
[small]#_connection_: lightuserdata +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkGetPhysicalDeviceXcbPresentationSupportKHR[vkGetPhysicalDeviceXcbPresentationSupportKHR] (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_xcb_surface[VK_KHR_xcb_surface] extension).#

[[create_xcb_surface]]
* _surface_ = *create_xcb_surface*(_instance_, _flags_, _connection_, _window_, [<<allocators, _allocator_>>]) +
[small]#_connection_: lightuserdata +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkCreateXcbSurfaceKHR[vkCreateXcbSurfaceKHR] (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_xcb_surface[VK_KHR_xcb_surface] extension).#

'''

[[get_physical_device_wayland_presentation_support]]
* _boolean_ = *get_physical_device_wayland_presentation_support*(_physdev_, _familyindex_, _wldisplay_) +
[small]#_wldisplay_: lightuserdata +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkGetPhysicalDeviceWaylandPresentationSupportKHR[vkGetPhysicalDeviceWaylandPresentationSupportKHR] (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_wayland_surface[VK_KHR_wayland_surface] extension).#

[[create_wayland_surface]]
* _surface_ = *create_wayland_surface*(_instance_, _flags_, _wldisplay_, _wlsurface_, [<<allocators, _allocator_>>]) +
[small]#_wldisplay_: lightuserdata +
_wlsurface_: lightuserdata +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkCreateWaylandSurfaceKHR[vkCreateWaylandSurfaceKHR] (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_wayland_surface[VK_KHR_wayland_surface] extension).#

'''

[[get_physical_device_mir_presentation_support]]
* _boolean_ = *get_physical_device_mir_presentation_support*(_physdev_, _familyindex_, _mirconnection_) +
[small]#_mirconnection_: lightuserdata +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkGetPhysicalDeviceMirPresentationSupportKHR[vkGetPhysicalDeviceMirPresentationSupportKHR] (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_mir_surface[VK_KHR_mir_surface] extension).#

[[create_mir_surface]]
* _surface_ = *create_mir_surface*(_instance_, _flags_, _mirconnection_, _mirsurface_, [<<allocators, _allocator_>>]) +
[small]#_mirconnection_: lightuserdata +
_mirsurface_: lightuserdata +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkCreateMirSurfaceKHR[vkCreateMirSurfaceKHR] (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_mir_surface[VK_KHR_mir_surface] extension).#


////

'''

[[create_android_surface]]
* _surface_ = *create_android_surface*(_instance_, _flags_, _awindow_, [<<allocators, _allocator_>>]) +
[small]#_awindow_: lightuserdata +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkCreateAndroidSurfaceKHR[vkCreateAndroidSurfaceKHR] (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_android_surface[VK_KHR_android_surface] extension).#

'''

[[get_physical_device_win32_presentation_support]]
* _boolean_ = *get_physical_device_win32_presentation_support*(_physdev_, _familyindex_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkGetPhysicalDeviceWin32PresentationSupportKHR[vkGetPhysicalDeviceWin32PresentationSupportKHR] (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_win32_surface[VK_KHR_win32_surface] extension).#

[[create_win32_surface]]
* _surface_ = *create_win32_surface*(_instance_, _flags_, _hinstance_, _hwnd_, [<<allocators, _allocator_>>]) +
[small]#_hinstance_: lightuserdata +
_hwnd: lightuserdata +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkCreateWin32SurfaceKHR[vkCreateWin32SurfaceKHR] (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_win32_surface[VK_KHR_win32_surface] extension).#

////

