
[[structs]]
== Structs

This section describes the tables used in MoonVulkan to pass Vulkan API structures 
from Lua to C and viceversa. 

The correspondence between the tables and the underlying C structs is almost one-to-one
footnote:[With respect to C structs, Lua tables don't have fields whose values can be inferred 
from other field values (for example counts, sizes and lengths), and in general all those
fields that can be dealt with by MoonVulkan in C without passing them to/from Lua, like
'sType' and 'pNext' fields.].
Fields in tables are named with https://en.wikipedia.org/wiki/Snake_case[snake_case] versions of their C equivalents 
(without the leading _p_'s denoting pointers in C), and have the same semantics.

When a table is passed from C to Lua, all its fields are always present unless otherwise
explicitly stated in the descriptions below.

When passing a table from Lua to C, if a field is annotated with *[R]* it is required and must
be explicitly set, otherwise it is optional. If an optional field is not set, the following
*default value(s)* will be used unless otherwise specified in the field's description:

* fields that admit a 'not present' encoding will be encoded as such,
* flags default to 0,
* enums default to the value indicated as default for their type in the <<enums, Enums>> section, +
* booleans default to _false_, +
* integers, floats, and numbers in general default to 0, +
* strings default to _NULL_ (not present).

(note that a default value may not necessarily be considered valid by the Vulkan API: 
if you need to check this, use the validation layers).

The tables are described as _fieldname_++:++_valuetype_ lists of fields, where _fieldname_ is
the key of the field in the Lua table, and _valuetype_ is the type its value must be of. 
The notation {_valuetype_} denotes an array of _valuetype_ elements (by 'array' we mean a table 
with 1-based integer keys and no gaps, a.k.a. 'sequence' in Lua's jargon).


'''

Basic types used in the table description that follow:

* [small]#*boolean*: a Lua boolean.#
* [small]#*integer*: a Lua integer.#
* [small]#*float*: a Lua number that fits in a _float32_.#
* [small]#*string*: a NUL terminated Lua string.#
* [small]#*binary string*: a Lua binary string.#

* [[timeout]]
[small]#*timeout* = integer (nanoseconds) or '_blocking_' or _nil_ (both for blocking).#

'''

* [[layerproperties]]
[small]#*layerproperties* = { +
_layer_name_: string, +
_spec_version_: integer, +
_implementation_version_: integer, +
_description_: string, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkLayerProperties[VkLayerProperties])#


* [[extensionproperties]]
[small]#*extensionproperties* = { +
_extension_name_: string, +
_spec_version_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkExtensionProperties[VkExtensionProperties])#

'''

* [[instancecreateinfo]]
[small]#*instancecreateinfo* = { +
_flags_: <<instancecreateflags, instancecreateflags>> +
_application_info_: <<applicationinfo, applicationinfo>> +
_enabled_layer_names_: {string} +
_enabled_extension_names_: {string} +
pass:[----] extensions ---- +
_disabled_validation_checks_: {<<validationcheck, _validationcheck_>>} (Note1), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkInstanceCreateInfo[VkInstanceCreateInfo]) +
Note1: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_EXT_validation_flags[VK_EXT_validation_flags] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkValidationFlagsEXT[VkValidationFlagsEXT]).#

[[applicationinfo]]
* [small]#*applicationinfo* = { +
_application_name_: string, +
_application_version_: integer, +
_engine_name_: string, +
_engine_version_: integer, +
_api_version_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkApplicationInfo[VkApplicationInfo])#

'''

* [[physicaldeviceproperties]]
[small]#*physicaldeviceproperties* = { +
_api_version_: integer, +
_driver_version_: integer, +
_vendor_id_: integer, +
_device_id_: integer, +
_device_type_: <<physicaldevicetype, physicaldevicetype>>, +
_device_name_: string, +
_pipeline_cache_uuid_: binary string (length = 16), +
_limits_: <<physicaldevicelimits, physicaldevicelimits>>, +
_sparse_properties_: <<physicaldevicesparseproperties, physicaldevicesparseproperties>>, +
pass:[----] extensions ---- +
_max_push_descriptors_: integer (Note1), +
_advanced_blend_max_color_attachments_: integer (Note2), +
_advanced_blend_independent_blend_: boolean (Note2), +
_advanced_blend_non_premultiplied_src_color_: boolean (Note2), +
_advanced_blend_non_premultiplied_dst_color_: boolean (Note2), +
_advanced_blend_correlated_overlap_: boolean (Note2), +
_advanced_blend_all_operations_: boolean (Note2), +
_filter_minmax_single_component_formats_: boolean (Note3), +
_filter_minmax_image_component_mapping_: boolean (Note3), +
_max_discard_rectangles_: integer (Note4), +
_device_uuid_: binary string (Note5), +
_driver_uuid_: binary string (Note5), +
_device_luid_: binary string (Note5), +
_device_node_mask_: integer (Note5), +
_device_luid_valid_: boolean(Note5), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceProperties2KHR[VkPhysicalDeviceProperties2KHR]) +
Note1: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_push_descriptor[VK_KHR_push_descriptor] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDevicePushDescriptorPropertiesKHR[VkPhysicalDevicePushDescriptorPropertiesKHR]). +
Note2: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_EXT_blend_operation_advanced[VK_EXT_blend_operation_advanced] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceBlendOperationAdvancedPropertiesEXT[VkPhysicalDeviceBlendOperationAdvancedPropertiesEXT]). +
Note3: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_EXT_sampler_filter_minmax[VK_EXT_sampler_filter_minmax] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceSamplerFilterMinmaxPropertiesEXT[VkPhysicalDeviceSamplerFilterMinmaxPropertiesEXT]). +
Note4: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_EXT_discard_rectangles[VK_EXT_discard_rectangles] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceDiscardRectanglePropertiesEXT[VkPhysicalDeviceDiscardRectanglePropertiesEXT]). +
Note5: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_external_memory_capabilities[VK_KHR_external_memory_capabilities] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceIDPropertiesKHR[VkPhysicalDeviceIDPropertiesKHR]).#

* [[physicaldeviceimageformatinfo]]
[small]#*physicaldeviceimageformatinfo* = { +
_format_: <<format,format>>, +
_type_: <<imagetype, imagetype>>, +
_tiling_: <<imagetiling, imagetiling>>, +
_usage_: <<imageusageflags, imageusageflags>>, +
_flags_: <<imagecreateflags, imagecreateflags>>, +
pass:[----] extensions ---- +
_handle_type_: <<externalmemoryhandletypeflags, externalmemoryhandletypeflags>> (Note1), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceImageFormatInfo2KHR[VkPhysicalDeviceImageFormatInfo2KHR]) +
Note1: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_external_memory_capabilities[VK_KHR_external_memory_capabilities] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceExternalImageFormatInfoKHR[VkPhysicalDeviceExternalImageFormatInfoKHR]).#

* [[physicaldevicelimits]]
[small]#*physicaldevicelimits* = { +
_max_image_dimension_1d_: integer, +
_max_image_dimension_2d_: integer, +
_max_image_dimension_3d_: integer, +
_max_image_dimension_cube_: integer, +
_max_image_array_layers_: integer, +
_max_texel_buffer_elements_: integer, +
_max_uniform_buffer_range_: integer, +
_max_storage_buffer_range_: integer, +
_max_push_constants_size_: integer, +
_max_memory_allocation_count_: integer, +
_max_sampler_allocation_count_: integer, +
_buffer_image_granularity_: integer, +
_sparse_address_space_size_: integer, +
_max_bound_descriptor_sets_: integer, +
_max_per_stage_descriptor_samplers_: integer, +
_max_per_stage_descriptor_uniform_buffers_: integer, +
_max_per_stage_descriptor_storage_buffers_: integer, +
_max_per_stage_descriptor_sampled_images_: integer, +
_max_per_stage_descriptor_storage_images_: integer, +
_max_per_stage_descriptor_input_attachments_: integer, +
_max_per_stage_resources_: integer, +
_max_descriptor_set_samplers_: integer, +
_max_descriptor_set_uniform_buffers_: integer, +
_max_descriptor_set_uniform_buffers_dynamic_: integer, +
_max_descriptor_set_storage_buffers_: integer, +
_max_descriptor_set_storage_buffers_dynamic_: integer, +
_max_descriptor_set_sampled_images_: integer, +
_max_descriptor_set_storage_images_: integer, +
_max_descriptor_set_input_attachments_: integer, +
_max_vertex_input_attributes_: integer, +
_max_vertex_input_bindings_: integer, +
_max_vertex_input_attribute_offset_: integer, +
_max_vertex_input_binding_stride_: integer, +
_max_vertex_output_components_: integer, +
_max_tessellation_generation_level_: integer, +
_max_tessellation_patch_size_: integer, +
_max_tessellation_control_per_vertex_input_components_: integer, +
_max_tessellation_control_per_vertex_output_components_: integer, +
_max_tessellation_control_per_patch_output_components_: integer, +
_max_tessellation_control_total_output_components_: integer, +
_max_tessellation_evaluation_input_components_: integer, +
_max_tessellation_evaluation_output_components_: integer, +
_max_geometry_shader_invocations_: integer, +
_max_geometry_input_components_: integer, +
_max_geometry_output_components_: integer, +
_max_geometry_output_vertices_: integer, +
_max_geometry_total_output_components_: integer, +
_max_fragment_input_components_: integer, +
_max_fragment_output_attachments_: integer, +
_max_fragment_dual_src_attachments_: integer, +
_max_fragment_combined_output_resources_: integer, +
_max_compute_shared_memory_size_: integer, +
_max_compute_work_group_count_: {integer}[3], +
_max_compute_work_group_invocations_: integer, +
_max_compute_work_group_size_: {integer}[3], +
_sub_pixel_precision_bits_: integer, +
_sub_texel_precision_bits_: integer, +
_mipmap_precision_bits_: integer, +
_max_draw_indexed_index_value_: integer, +
_max_draw_indirect_count_: integer, +
_max_sampler_lod_bias_: integer, +
_max_sampler_anisotropy_: float, +
_max_viewports_: integer, +
_max_viewport_dimensions_: {integer}[2], +
_viewport_bounds_range_: {float}[2], +
_viewport_sub_pixel_bits_: integer, +
_min_memory_map_alignment_: integer, +
_min_texel_buffer_offset_alignment_: integer, +
_minuniform_buffer_offset_alignment_: integer, +
_min_storage_buffer_offset_alignment_: integer, +
_min_texel_offset_: integer, +
_max_texel_offset_: integer, +
_min_texel_gather_offset_: integer, +
_max_texel_gather_offset_: integer, +
_min_interpolation_offset_: float, +
_max_interpolation_offset_: float, +
_sub_pixel_interpolation_offset_bits_: integer, +
_max_framebuffer_width_: integer, +
_max_framebuffer_height_: integer, +
_max_framebuffer_layers_: integer, +
_framebuffer_color_sample_counts_: <<samplecountflags, samplecountflags>>, +
_framebuffer_depth_sample_counts_: <<samplecountflags, samplecountflags>>, +
_framebuffer_stencil_sample_counts_: <<samplecountflags, samplecountflags>>, +
_framebuffer_no_attachments_sample_counts_: <<samplecountflags, samplecountflags>>, +
_max_color_attachments_: integer, +
_sampled_image_color_sample_counts_: <<samplecountflags, samplecountflags>>, +
_sampled_image_integer_sample_counts_: <<samplecountflags, samplecountflags>>, +
_sampled_image_depth_sample_counts_: <<samplecountflags, samplecountflags>>, +
_sampled_image_stencil_sample_counts_: <<samplecountflags, samplecountflags>>, +
_storage_image_sample_counts_: <<samplecountflags, samplecountflags>>, +
_max_sample_mask_words_: integer, +
_timestamp_compute_and_graphics_: boolean, +
_timestamp_period_: float, +
_max_clip_distances_: integer, +
_max_cull_distances_: integer, +
_max_combined_clip_and_cull_distances_: integer, +
_discrete_queue_priorities_: integer, +
_point_size_range_: {float}[2], +
_line_width_range_: {float}[2], +
_point_size_granularity_: float, +
_line_width_granularity_: float, +
_strict_lines_: boolean, +
_standard_sample_locations_: boolean, +
_optimal_buffer_copy_offset_alignment_: integer, +
_optimal_buffer_copy_row_pitch_alignment_: integer, +
_non_coherent_atom_size_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceLimits[VkPhysicalDeviceLimits])#

* [[physicaldevicesparseproperties]]
[small]#*physicaldevicesparseproperties* = { +
_residency_standard_2d_block_shape_: boolean, +
_residency_standard_2d_multisample_block_shape_: boolean, +
_residency_standard_3d_block_shape_: boolean, +
_residency_aligned_mip_size_: boolean, +
_residency_non_resident_strict_: boolean, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceSparseProperties[VkPhysicalDeviceSparseProperties])#

* [[physicaldevicefeatures]]
[small]#*physicaldevicefeatures* = { +
_robust_buffer_access_: boolean, +
_full_draw_index_uint_32_: boolean, +
_image_cube_array_: boolean, +
_independent_blend_: boolean, +
_geometry_shader_: boolean, +
_tessellation_shader_: boolean, +
_sample_rate_shading_: boolean, +
_dual_src_blend_: boolean, +
_logic_op_: boolean, +
_multi_draw_indirect_: boolean, +
_draw_indirect_first_instance_: boolean, +
_depth_clamp_: boolean, +
_depth_bias_clamp_: boolean, +
_fill_mode_non_solid_: boolean, +
_depth_bounds_: boolean, +
_wide_lines_: boolean, +
_large_points_: boolean, +
_alpha_to_one_: boolean, +
_multi_viewport_: boolean, +
_sampler_anisotropy_: boolean, +
_texture_compression_etc2_: boolean, +
_texture_compression_astc_ldr_: boolean, +
_texture_compression_bc_: boolean, +
_occlusion_query_precise_: boolean, +
_pipeline_statistics_query_: boolean, +
_vertex_pipeline_stores_and_atomics_: boolean, +
_fragment_stores_and_atomics_: boolean, +
_shader_tessellation_and_geometry_point_size_: boolean, +
_shader_image_gather_extended_: boolean, +
_shader_storage_image_extended_formats_: boolean, +
_shader_storage_image_multisample_: boolean, +
_shader_storage_image_read_without_format_: boolean, +
_shader_storage_image_write_without_format_: boolean, +
_shader_uniform_buffer_array_dynamic_indexing_: boolean, +
_shader_sampled_image_array_dynamic_indexing_: boolean, +
_shader_storage_buffer_array_dynamic_indexing_: boolean, +
_shader_storage_image_array_dynamic_indexing_: boolean, +
_shader_clip_distance_: boolean, +
_shader_cull_distance_: boolean, +
_shader_float_64_: boolean, +
_shader_int_64_: boolean, +
_shader_int_16_: boolean, +
_shader_resource_residency_: boolean, +
_shader_resource_min_lod_: boolean, +
_sparse_binding_: boolean, +
_sparse_residency_buffer_: boolean, +
_sparse_residency_image_2d_: boolean, +
_sparse_residency_image_3d_: boolean, +
_sparse_residency_2_samples_: boolean, +
_sparse_residency_4_samples_: boolean, +
_sparse_residency_8_samples_: boolean, +
_sparse_residency_16_samples_: boolean, +
_sparse_residency_aliased_: boolean, +
_variable_multisample_rate_: boolean, +
_inherited_queries_: boolean, +
pass:[----] extensions ---- +
_storage_buffer_16bit_access_: boolean (Note1), +
_uniform_and_storage_buffer_16bit_access_: boolean (Note1), +
_storage_push_constant_16_: boolean (Note1), +
_storage_input_output_16_: boolean (Note1), +
_variable_pointers_storage_buffer_: boolean (Note2), +
_variable_pointers_: boolean (Note2), +
_advanced_blend_coherent_operations_: boolean (Note3), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceFeatures2KHR[VkPhysicalDeviceFeatures2KHR]) +
Note1: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_16bit_storage[VK_KHR_16bit_storage] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDevice16BitStorageFeaturesKHR[VkPhysicalDevice16BitStorageFeaturesKHR]). +
Note2: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_variable_pointers[VK_KHR_variable_pointers] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceVariablePointerFeaturesKHR[VkPhysicalDeviceVariablePointerFeaturesKHR]). +
Note3: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_EXT_blend_operation_advanced[VK_EXT_blend_operation_advanced] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceBlendOperationAdvancedFeaturesEXT[VkPhysicalDeviceBlendOperationAdvancedFeaturesEXT]).#


* [[queuefamilyproperties]]
[small]#*queuefamilyproperties* = { +
_queue_family_index_: integer, +
_queue_flags_: <<queueflags, queueflags>>, +
_queue_count_: integer, +
_timestamp_valid_bits_: integer, +
_min_image_transfer_granularity_: <<extent3d, extent3d>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkQueueFamilyProperties[VkQueueFamilyProperties])#

* [[physicaldevicememoryproperties]]
[small]#*physicaldevicememoryproperties* = { +
_memory_types_: {<<memorytype, memorytype>>}, +
_memory_heaps_: {<<memoryheap, memoryheap>>}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceMemoryProperties[VkPhysicalDeviceMemoryProperties])#

* [[memorytype]]
[small]#*memorytype* = { +
_memory_type_index_: integer, +
_property_flags_: <<memorypropertyflags, memorypropertyflags>>, +
_heap_index_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkMemoryType[VkMemoryType])#

* [[memoryheap]]
[small]#*memoryheap* = { +
_memory_heap_index_: integer, +
_size_: integer, +
_flags_: <<memoryheapflags, memoryheapflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkMemoryHeap[VkMemoryHeap])#


* [[formatproperties]]
[small]#*formatproperties* = { +
_linear_tiling_features_: <<formatfeatureflags, formatfeatureflags>>, +
_optimal_tiling_features_: <<formatfeatureflags, formatfeatureflags>>, +
_buffer_features_: <<formatfeatureflags, formatfeatureflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkFormatProperties[VkFormatProperties])#


* [[imageformatproperties]]
[small]#*imageformatproperties* = { +
_max_extent_: <<extent3d, extent3d>>, +
_max_mip_levels_: integer, +
_max_array_layers_: integer, +
_sample_counts_: integer, +
_max_resource_size_: integer, +
pass:[----] extensions ---- +
_external_memory_properties_: <<externalmemoryproperties, externalmemoryproperties>> (Note1), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkImageFormatProperties[VkImageFormatProperties]) +
Note1: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_external_memory_capabilities[VK_KHR_external_memory_capabilities] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkExternalImageFormatPropertiesKHR[VkExternalImageFormatPropertiesKHR]).#

* [[physicaldevicesparseimageformatinfo]]
[small]#*physicaldevicesparseimageformatinfo* = { +
_format_: <<format,format>>, +
_type_: <<imagetype, imagetype>>, +
_samples_: <<samplecountflags, samplecountflags>>, +
_usage_: <<imageusageflags, imageusageflags>>, +
_tiling_: <<imagetiling, imagetiling>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceSparseImageFormatInfo2KHR[VkPhysicalDeviceSparseImageFormatInfo2KHR])#

* [[sparseimageformatproperties]]
[small]#*sparseimageformatproperties* = { +
_aspect_mask_: <<imageaspectflags, imageaspectflags>>, +
_image_granularity_: <<extent3d, extent3d>>, +
_flags_: <<sparseimageformatflags, sparseimageformatflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSparseImageFormatProperties[VkSparseImageFormatProperties])#

* [[externalmemoryproperties]]
[small]#*externalmemoryproperties* = { +
_external_memory_features_: <<externalmemoryfeatureflags, externalmemoryfeatureflags>>, +
_export_from_imported_handle_types_: <<externalmemoryhandletypeflags, externalmemoryhandletypeflags>>, +
_compatible_handle_types_: <<externalmemoryhandletypeflags, externalmemoryhandletypeflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkExternalMemoryPropertiesKHR[VkExternalMemoryPropertiesKHR])#

* [[physicaldeviceexternalbufferinfo]]
[small]#*physicaldeviceexternalbufferinfo* = { +
_flags_: <<buffercreateflags, buffercreateflags>>, +
_usage_: <<bufferusageflags, bufferusageflags>>, +
_handle_type_: <<externalmemoryhandletypeflags, externalmemoryhandletypeflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceExternalBufferInfoKHR[VkPhysicalDeviceExternalBufferInfoKHR])#

* [[externalbufferproperties]]
[small]#*externalbufferproperties* = { +
_external_memory_properties_: <<externalmemoryproperties, externalmemoryproperties>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkExternalBufferPropertiesKHR[VkExternalBufferPropertiesKHR])#

* [[physicaldeviceexternalfenceinfo]]
[small]#*physicaldeviceexternalfenceinfo* = { +
_handle_type_: <<externalfencehandletypeflags, externalfencehandletypeflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceExternalFenceInfoKHR[VkPhysicalDeviceExternalFenceInfoKHR])#

* [[externalfenceproperties]]
[small]#*externalfenceproperties* = { +
_export_from_imported_handle_types_: <<externalfencehandletypeflags, externalfencehandletypeflags>>, +
_compatible_handle_types_: <<externalfencehandletypeflags, externalfencehandletypeflags>>, +
_external_fence_features_: <<externalfencefeatureflags, externalfencefeatureflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkExternalFencePropertiesKHR[VkExternalFencePropertiesKHR])#


* [[physicaldeviceexternalsemaphoreinfo]]
[small]#*physicaldeviceexternalsemaphoreinfo* = { +
_handle_type_: <<externalsemaphorehandletypeflags, externalsemaphorehandletypeflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceExternalSemaphoreInfoKHR[VkPhysicalDeviceExternalSemaphoreInfoKHR])#

* [[externalsemaphoreproperties]]
[small]#*externalsemaphoreproperties* = { +
_export_from_imported_handle_types_: <<externalsemaphorehandletypeflags, externalsemaphorehandletypeflags>>, +
_compatible_handle_types_: <<externalsemaphorehandletypeflags, externalsemaphorehandletypeflags>>, +
_external_semaphore_features_: <<externalsemaphorefeatureflags, externalsemaphorefeatureflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkExternalSemaphorePropertiesKHR[VkExternalSemaphorePropertiesKHR])#

'''

* [[devicecreateinfo]]
[small]#*devicecreateinfo* = { +
_flags_: <<devicecreateflags, devicecreateflags>>, +
_queue_create_infos_: {<<devicequeuecreateinfo, devicequeuecreateinfo>>} *[R]*, +
_enabled_layer_names_: {string} _(DEPRECATED)_, +
_enabled_extension_names_: {_string_}, +
_enabled_features_: {<<physicaldevicefeatures, physicaldevicefeatures>>}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDeviceCreateInfo[VkDeviceCreateInfo])#


* [[devicequeuecreateinfo]]
[small]#*devicequeuecreateinfo* = { +
_flags_: <<devicequeuecreateflags, devicequeuecreateflags>>, +
_queue_family_index_: integer, +
_queue_priorities_: {float} *[R]*, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDeviceQueueCreateInfo[VkDeviceQueueCreateInfo])#

'''

* [[submitinfo]]
[small]#*submitinfo* = { +
_wait_semaphores_: {<<semaphore, semaphore>>}, +
_wait_dst_stage_mask_: {<<pipelinestageflags, pipelinestageflags>>}, +
_command_buffers_: {<<command_buffer, command_buffer>>}, +
_signal_semaphores_: {<<semaphore, semaphore>>}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSubmitInfo[VkSubmitInfo])#

* [[bindsparseinfo]]
[small]#*bindsparseinfo* = { +
_wait_semaphores_: {<<semaphore, semaphore>>}, +
_buffer_binds_: {<<sparsebuffermemorybindinfo, sparsebuffermemorybindinfo>>}, +
_image_opaque_binds_: {<<sparseimageopaquememorybindinfo, sparseimageopaquememorybindinfo>>}, +
_image_binds_: {<<sparseimagememorybindinfo, sparseimagememorybindinfo>>}, +
_signal_semaphores_: {<<semaphore, semaphore>>}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkBindSparseInfo[VkBindSparseInfo])#

* [[sparsebuffermemorybindinfo]]
[small]#*sparsebuffermemorybindinfo* = { +
_buffer_: <<buffer, buffer>> *[R]*, +
_binds_: {<<sparsememorybind, sparsememorybind>>} *[R]*, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSparseBufferMemoryBindInfo[VkSparseBufferMemoryBindInfo])#

* [[sparseimageopaquememorybindinfo]]
[small]#*sparseimageopaquememorybindinfo* = { +
_image_: <<image, image>> *[R]*, +
_binds_: {<<sparsememorybind, sparsememorybind>>} *[R]*, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSparseImageOpaqueMemoryBindInfo[VkSparseImageOpaqueMemoryBindInfo])#

* [[sparsememorybind]]
[small]#*sparsememorybind* = { +
_resource_offset_: integer, +
_size_: integer, +
_memory_: <<device_memory, device_memory>> *[R]*, +
_memory_offset_: integer, +
_flags_: <<sparsememorybindflags, sparsememorybindflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSparseMemoryBind[VkSparseMemoryBind])#


* [[sparseimagememorybindinfo]]
[small]#*sparseimagememorybindinfo* = { +
_image_: <<image, image>> *[R]*, +
_binds_: {<<sparseimagememorybind, sparseimagememorybind>>} *[R]*, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSparseImageMemoryBindInfo[VkSparseImageMemoryBindInfo])#

* [[sparseimagememorybind]]
[small]#*sparseimagememorybind* = { +
_subresource_: <<imagesubresource, imagesubresource>> *[R]*, +
_offset_: <<offset3d, offset3d>>, +
_extent_: <<extent3d, extent3d>>, +
_memory_: <<device_memory, device_memory>> *[R]*, +
_memory_offset_: integer, +
_flags_: <<sparseimagememorybindflags, sparseimagememorybindflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSparseImageMemoryBind[VkSparseImageMemoryBind])#

'''

* [[commandpoolcreateinfo]]
[small]#*commandpoolcreateinfo* = { +
_flags_: <<commandpoolcreateflags, commandpoolcreateflags>>, +
_queue_family_index_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkCommandPoolCreateInfo[VkCommandPoolCreateInfo])#

* [[commandbufferallocateinfo]]
[small]#*commandbufferallocateinfo* = { +
_level_: <<commandbufferlevel, commandbufferlevel>> *[R]*, +
_command_buffer_count_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkCommandBufferAllocateInfo[VkCommandBufferAllocateInfo])#

* [[commandbufferbegininfo]]
[small]#*commandbufferbegininfo* = { +
_flags_: <<commandbufferusageflags, commandbufferusageflags>>, +
_inheritance_info_: <<commandbufferinheritanceinfo, commandbufferinheritanceinfo>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkCommandBufferBeginInfo[VkCommandBufferBeginInfo])#


* [[commandbufferinheritanceinfo]]
[small]#*commandbufferinheritanceinfo* = { +
_render_pass_: <<render_pass, render_pass>> *[R]*, +
_subpass_: integer, +
_framebuffer_: <<framebuffer, framebuffer>> *[R]*, +
_occlusion_query_enable_: boolean, +
_query_flags_: <<querycontrolflags, querycontrolflags>>, +
_pipeline_statistics_: <<querypipelinestatisticflags, querypipelinestatisticflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkCommandBufferInheritanceInfo[VkCommandBufferInheritanceInfo])#

'''

* [[fencecreateinfo]]
[small]#*fencecreateinfo* = { +
_flags_: <<fencecreateflags, fencecreateflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkFenceCreateInfo[VkFenceCreateInfo])#

* [[deviceeventinfo]]
[small]#*deviceeventinfo* = { +
_device_event_: <<deviceeventtype, deviceeventtype>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDeviceEventInfoEXT[VkDeviceEventInfoEXT])#

* [[displayeventinfo]]
[small]#*displayeventinfo* = { +
_display_event_: <<displayeventtype, displayeventtype>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDisplayEventInfoEXT[VkDisplayEventInfoEXT])#

* [[semaphorecreateinfo]]
[small]#*semaphorecreateinfo* = { +
_flags_: <<semaphorecreateflags, semaphorecreateflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSemaphoreCreateInfo[VkSemaphoreCreateInfo])#

* [[eventcreateinfo]]
[small]#*eventcreateinfo* = { +
_flags_: <<eventcreateflags, eventcreateflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkEventCreateInfo[VkEventCreateInfo])#

'''

* [[renderpasscreateinfo]]
[small]#*renderpasscreateinfo* = { +
_flags_: <<renderpasscreateflags, renderpasscreateflags>>, +
_subpasses_: {<<subpassdescription, subpassdescription>>} *[R]*, +
_attachments_: {<<attachmentdescription, attachmentdescription>>}, +
_dependencies_: {<<subpassdependency, subpassdependency>>}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkRenderPassCreateInfo[VkRenderPassCreateInfo])#


* [[attachmentdescription]]
[small]#*attachmentdescription* = { +
_flags_: <<attachmentdescriptionflags, attachmentdescriptionflags>>, +
_format_: <<format, format>>, +
_samples_: <<samplecountflags, samplecountflags>> (defaults to 1), +
_load_op_: <<attachmentloadop, attachmentloadop>>, +
_store_op_: <<attachmentstoreop, attachmentstoreop>>, +
_stencil_load_op_: <<attachmentloadop, attachmentloadop>>, +
_stencil_store_op_: <<attachmentstoreop, attachmentstoreop>>, +
_initial_layout_: <<imagelayout, imagelayout>>, +
_final_layout_: <<imagelayout, imagelayout>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkAttachmentDescription[VkAttachmentDescription])#


* [[subpassdescription]]
[small]#*subpassdescription* = { +
_flags_: <<subpassdescriptionflags, subpassdescriptionflags>>, +
_pipeline_bind_point_: <<pipelinebindpoint, pipelinebindpoint>>, +
_input_attachments_: {<<attachmentreference, attachmentreference>>}, +
_color_attachments_: {<<attachmentreference, attachmentreference>>}, +
_resolve_attachments_: {<<attachmentreference, attachmentreference>>}, +
_depth_stencil_attachment_: <<attachmentreference, attachmentreference>>, +
_preserve_attachments_: {integer}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSubpassDescription[VkSubpassDescription])#

* [[attachmentreference]]
[small]#*attachmentreference* = { +
_attachment_: integer or '_unused_' (defaults to '_unused_'), +
_layout_: <<imagelayout, imagelayout>> *[R]*, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkAttachmentReference[VkAttachmentReference])#

* [[subpassdependency]]
[small]#*subpassdependency* = { +
_src_subpass_: integer or '_external_', +
_dst_subpass_: integer or '_external_', +
_src_stage_mask_: <<pipelinestageflags, pipelinestageflags>>, +
_dst_stage_mask_: <<pipelinestageflags, pipelinestageflags>>, +
_src_access_mask_: <<accessflags, accessflags>>, +
_dst_access_mask_: <<accessflags, accessflags>>, +
_dependency_flags_: <<dependencyflags, dependencyflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSubpassDependency[VkSubpassDependency])#

'''

* [[framebuffercreateinfo]]
[small]#*framebuffercreateinfo* = { +
_flags_: <<framebuffercreateflags, framebuffercreateflags>>, +
_render_pass_: <<render_pass, render_pass>> *[R]*, +
_width_: integer, +
_height_: integer, +
_layers_: integer (defaults to 1), +
_attachments_: {<<image_view, image_view>>}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkFramebufferCreateInfo[VkFramebufferCreateInfo])#

'''

* [[shadermodulecreateinfo]]
[small]#*shadermodulecreateinfo* = { +
_flags_: <<shadermodulecreateflags, shadermodulecreateflags>>, +
_code_: binary string *[R]*, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkShaderModuleCreateInfo[VkShaderModuleCreateInfo])#

'''

* [[pipelinecachecreateinfo]]
[small]#*pipelinecachecreateinfo* = { +
_flags_: <<pipelinecachecreateflags, pipelinecachecreateflags>>, +
_initial_data_: binary string, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPipelineCacheCreateInfo[VkPipelineCacheCreateInfo])#

'''

* [[buffercreateinfo]]
[small]#*buffercreateinfo* = { +
_flags_: <<buffercreateflags, buffercreateflags>>, +
_size_: integer +
_usage_: <<bufferusageflags, bufferusageflags>>, +
_sharing_mode_: <<sharingmode, sharingmode>>, +
_queue_family_indices_: {integer}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkBufferCreateInfo[VkBufferCreateInfo])#

* [[bufferviewcreateinfo]]
[small]#*bufferviewcreateinfo* = { +
_flags_: <<bufferviewcreateflags, bufferviewcreateflags>>, +
_format_: <<format, format>>, +
_offset_: integer, +
_range_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkBufferViewCreateInfo[VkBufferViewCreateInfo])#

'''

* [[imagecreateinfo]]
[small]#*imagecreateinfo* = { +
_flags_: <<imagecreateflags, imagecreateflags>>, +
_image_type_: <<imagetype, imagetype>>, +
_format_: <<format, format>>, +
_extent_: <<extent3d, extent3d>>, +
_mip_levels_: integer (defaults to 1), +
_array_layers_: integer (defaults to 1), +
_samples_: <<samplecountflags, samplecountflags>> (defaults to 1), +
_tiling_: <<imagetiling, imagetiling>>, +
_usage_: <<imageusageflags, imageusageflags>>, +
_initial_layout_: <<imagelayout, imagelayout>>, +
_sharing_mode_: <<sharingmode, sharingmode>>, +
_queue_family_indices_: {integer}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkImageCreateInfo[VkImageCreateInfo])#

* [[imageviewcreateinfo]]
[small]#*imageviewcreateinfo* = { +
_flags_: <<imageviewcreateflags, imageviewcreateflags>>, +
_view_type_: <<imageviewtype, imageviewtype>> *[R]*, +
_format_: <<format, format>>, +
_components_: <<componentmapping, componentmapping>>, +
_subresource_range_: <<imagesubresourcerange, imagesubresourcerange>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkImageViewCreateInfo[VkImageViewCreateInfo])#

'''

* [[samplercreateinfo]]
[small]#*samplercreateinfo* = { +
_flags_: <<samplercreateflags, samplercreateflags>>, +
_mag_filter_: <<filter, filter>>, +
_min_filter_: <<filter, filter>>, +
_mipmap_mode_: <<samplermipmapmode, samplermipmapmode>>, +
_address_mode_u_: <<sampleraddressmode, sampleraddressmode>>, +
_address_mode_v_: <<sampleraddressmode, sampleraddressmode>>, +
_address_mode_w_: <<sampleraddressmode, sampleraddressmode>>, +
_mip_lod_bias_: float, +
_anisotropy_enable_: boolean, +
_max_anisotropy_: float, +
_compare_enable_: boolean, +
_compare_op_: <<compareop, compareop>>, +
_min_lod_: float, +
_max_lod_: float, +
_border_color_: <<bordercolor, bordercolor>>, +
_unnormalized_coordinates_: boolean, +
pass:[----] extensions ---- +
_reduction_mode_: <<samplerreductionmode, samplerreductionmode>> (Note1), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSamplerCreateInfo[VkSamplerCreateInfo]) +
Note1: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_EXT_sampler_filter_minmax[VK_EXT_sampler_filter_minmax] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSamplerReductionModeCreateInfoEXT[VkSamplerReductionModeCreateInfoEXT]).#

'''
* [[mappedmemoryrange]]
[small]#*mappedmemoryrange* = { +
_memory_: <<device_memory, device_memory>> *[R]*, +
_offset_: integer, +
_size_: integer or '_whole size_' (defaults to '_whole size_'), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkMappedMemoryRange[VkMappedMemoryRange])#

'''

* [[memoryallocateinfo]]
[small]#*memoryallocateinfo* = { +
_allocation_size_: integer, +
_memory_type_index_: integer, +
pass:[----] extensions ---- +
_image_: <<image, image>> (Note1), +
_buffer_: <<buffer, buffer>> (Note1), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkMemoryAllocateInfo[VkMemoryAllocateInfo]) +
Note1: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_dedicated_allocation[VK_KHR_dedicated_allocation] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkMemoryDedicatedAllocateInfoKHR[VkMemoryDedicatedAllocateInfoKHR])#

'''

* [[memoryrequirements]]
[small]#*memoryrequirements* = { +
_size_: integer, +
_alignment_: integer, +
_memory_type_bits_: integer, +
pass:[----] extensions ---- +
_prefers_dedicated_allocation_: boolean (Note1), +
_requires_dedicated_allocation_: boolean (Note1), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkMemoryRequirements2KHR[VkMemoryRequirements2KHR]) +
Note1: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_dedicated_allocation[VK_KHR_dedicated_allocation] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkMemoryDedicatedRequirementsKHR[VkMemoryDedicatedRequirementsKHR])#


* [[sparseimagememoryrequirements]]
[small]#*sparseimagememoryrequirements* = { +
_format_properties_: <<sparseimageformatproperties, sparseimageformatproperties>>, +
_image_mip_tail_first_lod_: integer, +
_image_mip_tail_size_: integer, +
_image_mip_tail_offset_: integer, +
_image_mip_tail_stride_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSparseImageMemoryRequirements[VkSparseImageMemoryRequirements])#

* [[subresourcelayout]]
[small]#*subresourcelayout* = { +
_offset_: integer, +
_size_: integer, +
_row_pitch_: integer, +
_array_pitch_: integer, +
_depth_pitch_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSubresourceLayout[VkSubresourceLayout])#


* [[imagesubresource]]
[small]#*imagesubresource* = { +
_aspect_mask_: <<imageaspectflags, imageaspectflags>>, +
_mip_level_: integer, +
_array_layer_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkImageSubresource[VkImageSubresource]) +
<<constructors, Constructor>>: *imagesubresource*(_aspect_mask_, _mip_level_, _array_layer_)#

* [[imagesubresourcerange]]
[small]#*imagesubresourcerange* = { +
_aspect_mask_: <<imageaspectflags, imageaspectflags>>, +
_base_mip_level_: integer, +
_level_count_: integer or '_remaining_' (defaults to 1), +
_base_array_layer_: integer, +
_layer_count_: integer or '_remaining_' (defaults to 1), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkImageSubresourceRange[VkImageSubresourceRange]) +
<<constructors, Constructor>>: *imagesubresourcerange*(_aspect_mask_, _base_mip_level_, _level_count_, _base_array_layer_, _layer_count_)#

'''

* [[descriptorsetlayoutcreateinfo]]
[small]#*descriptorsetlayoutcreateinfo* = { +
_flags_: <<descriptorsetlayoutcreateflags, descriptorsetlayoutcreateflags>>, +
_bindings_: {<<descriptorsetlayoutbinding, descriptorsetlayoutbinding>>}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDescriptorSetLayoutCreateInfo[VkDescriptorSetLayoutCreateInfo])#

* [[descriptorsetlayoutbinding]]
[small]#*descriptorsetlayoutbinding* = { +
_binding_: integer, +
_descriptor_type_: <<descriptortype, descriptortype>> *[R]*, +
_descriptor_count_: integer, +
_stage_flags_: <<shaderstageflags, shaderstageflags>>, +
_immutable_samplers_: {<<sampler, sampler>>}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDescriptorSetLayoutBinding[VkDescriptorSetLayoutBinding]) +
<<constructors, Constructor>>: *descriptorsetlayoutbinding*(_binding_, _descriptor_type_, _descriptor_count_, _stage_flags_, {_immutable_samplers_})#

'''

* [[pipelinelayoutcreateinfo]]
[small]#*pipelinelayoutcreateinfo* = { +
_flags_: <<pipelinelayoutcreateflags, pipelinelayoutcreateflags>>, +
_set_layouts_: {<<descriptor_set_layout, descriptor_set_layout>>}, +
_push_constant_ranges_: {<<pushconstantrange, pushconstantrange>>}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPipelineLayoutCreateInfo[PipelineLayoutCreateInfo])#


* [[pushconstantrange]]
[small]#*pushconstantrange* = { +
_stage_flags_: <<shaderstageflags, shaderstageflags>>, +
_offset_: integer, +
_size_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPushConstantRange[VkPushConstantRange]) +
<<constructors, Constructor>>: *pushconstantrange*(_stage_flags_, _offset_, _size_)#

'''

* [[descriptorpoolcreateinfo]]
[small]#*descriptorpoolcreateinfo* = { +
_flags_: <<descriptorpoolcreateflags, descriptorpoolcreateflags>>, +
_max_sets_: integer, +
_pool_sizes_: {<<descriptorpoolsize, descriptorpoolsize>>}, *[R]* +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDescriptorPoolCreateInfo[VkDescriptorPoolCreateInfo])#

* [[descriptorpoolsize]]
[small]#*descriptorpoolsize* = { +
_type_: <<descriptortype, descriptortype>> *[R]*, +
_descriptor_count_: integer (defaults to 1), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDescriptorPoolSize[VkDescriptorPoolSize])#

'''

* [[descriptorsetallocateinfo]]
[small]#*descriptorsetallocateinfo* = { +
_set_layouts_: <<descriptor_set_layout, descriptor_set_layout>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDescriptorSetAllocateInfo[VkDescriptorSetAllocateInfo])#

'''

* [[descriptorimageinfo]]
[small]#*descriptorimageinfo* = { +
_sampler_: <<sampler, sampler>> *[R]*, +
_image_view_: <<image_view, image_view>> *[R]*, +
_image_layout_: <<imagelayout, imagelayout>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDescriptorImageInfo[VkDescriptorImageInfo])#

* [[descriptorbufferinfo]]
[small]#*descriptorbufferinfo* = { +
_buffer_: <<buffer, buffer>> *[R]*, +
_offset_: integer, +
_range_: integer or '_whole size_' (defaults to '_whole size_'), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDescriptorBufferInfo[VkDescriptorBufferInfo])#

* [[writedescriptorset]]
[small]#*writedescriptorset* = { +
_dst_set_: <<descriptor_set, descriptor_set>> *[R]*, +
_dst_binding_: integer, +
_dst_array_element_: integer, +
_descriptor_type_: <<descriptortype, descriptortype>> *[R]*, +
_image_info_: {<<descriptorimageinfo, descriptorimageinfo>>}, +
_buffer_info_: {<<descriptorbufferinfo, descriptorbufferinfo>>}, +
_texel_buffer_view_: {<<buffer_view, buffer_view>>}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkWriteDescriptorSet[VkWriteDescriptorSet])#

* [[copydescriptorset]]
[small]#*copydescriptorset* = { +
_src_set_: <<descriptor_set, descriptor_set>> *[R]*, +
_src_binding_: integer, +
_src_array_element_: integer, +
_dst_set_: <<descriptor_set, descriptor_set>> *[R]*, +
_dst_binding_: integer, +
_dst_array_element_: integer, +
_descriptor_count_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkCopyDescriptorSet[VkCopyDescriptorSet])#

'''
* [[querypoolcreateinfo]]
[small]#*querypoolcreateinfo* = { +
_flags_: <<querypoolcreateflags, querypoolcreateflags>>, +
_query_type_: <<querytype, querytype>> *[R]*, +
_query_count_: integer, +
_pipeline_statistics_: <<querypipelinestatisticflags, querypipelinestatisticflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkQueryPoolCreateInfo[VkQueryPoolCreateInfo])#

'''

* [[graphicspipelinecreateinfo]]
[small]#*graphicspipelinecreateinfo* = { +
_flags_: <<pipelinecreateflags, pipelinecreateflags>>, +
_stages_: {<<pipelineshaderstagecreateinfo, pipelineshaderstagecreateinfo>>} *[R]*, +
_vertex_input_state_: <<pipelinevertexinputstatecreateinfo, pipelinevertexinputstatecreateinfo>> *[R]*, +
_input_assembly_state_: <<pipelineinputassemblystatecreateinfo, pipelineinputassemblystatecreateinfo>> *[R]*, +
_tessellation_state_: <<pipelinetessellationstatecreateinfo, pipelinetessellationstatecreateinfo>>, +
_viewport_state_: <<pipelineviewportstatecreateinfo, pipelineviewportstatecreateinfo>>, +
_rasterization_state_: <<pipelinerasterizationstatecreateinfo, pipelinerasterizationstatecreateinfo>> *[R]*, +
_multisample_state_: <<pipelinemultisamplestatecreateinfo, pipelinemultisamplestatecreateinfo>>, +
_depth_stencil_state_: <<pipelinedepthstencilstatecreateinfo, pipelinedepthstencilstatecreateinfo>>, +
_color_blend_state_: <<pipelinecolorblendstatecreateinfo, pipelinecolorblendstatecreateinfo>>, +
_dynamic_state_: <<pipelinedynamicstatecreateinfo, pipelinedynamicstatecreateinfo>>, +
_layout_: <<pipeline_layout, pipeline_layout>> *[R]*, +
_render_pass_: <<render_pass, render_pass>> *[R]*, +
_subpass_: integer, +
_base_pipeline_handle_: <<pipeline, pipeline>>, +
_base_pipeline_index_: integer, +
pass:[----] extensions ---- +
_color_blend_advanced_state_: <<pipelinecolorblendadvancedstatecreateinfo, pipelinecolorblendadvancedstatecreateinfo>> (Note1), +
_discard_rectangle_state_: <<pipelinediscardrectanglestatecreateinfo, pipelinediscardrectanglestatecreateinfo>> (Note2), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkGraphicsPipelineCreateInfo[VkGraphicsPipelineCreateInfo]) +
Note1: Requires the https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_EXT_blend_operation_advanced[VK_EXT_blend_operation_advanced] extension and the _color_blend_state_ field. +
Note2: Requires the https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_EXT_discard_rectangles[VK_EXT_discard_rectangles] extension.#

* [[computepipelinecreateinfo]]
[small]#*computepipelinecreateinfo* = { +
_flags_: <<pipelinecreateflags, pipelinecreateflags>>, +
_stage_: <<pipelineshaderstagecreateinfo, pipelineshaderstagecreateinfo>> *[R]*, +
_layout_: <<pipeline_layout, pipeline_layout>> *[R]*, +
_base_pipeline_handle_: <<pipeline, pipeline>>, +
_base_pipeline_index_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkComputePipelineCreateInfo[VkComputePipelineCreateInfo])#


* [[pipelineshaderstagecreateinfo]]
[small]#*pipelineshaderstagecreateinfo* = { +
_flags_: <<pipelineshaderstagecreateflags, pipelineshaderstagecreateflags>>, +
_stage_: <<shaderstageflags, shaderstageflags>>, +
_module_: <<shader_module, shader_module>> *[R]*, +
_name_: string (defaults to '_main_'), +
_specialization_info_: <<specializationinfo, specializationinfo>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPipelineShaderStageCreateInfo[VkPipelineShaderStageCreateInfo])#

* [[specializationinfo]]
[small]#*specializationinfo* = { +
_map_entries_: {<<specializationmapentry, specializationmapentry>>}, +
_data_: binary string *[R]*, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSpecializationInfo[VkSpecializationInfo])#

* [[specializationmapentry]]
[small]#*specializationmapentry* = { +
_constant_id_: integer, +
_offset_: integer, +
_size_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSpecializationMapEntry[VkSpecializationMapEntry])#


* [[pipelinevertexinputstatecreateinfo]]
[small]#*pipelinevertexinputstatecreateinfo* = { +
_flags_: <<pipelinevertexinputstatecreateflags, pipelinevertexinputstatecreateflags>>, +
_vertex_binding_descriptions_: {<<vertexinputbindingdescription, vertexinputbindingdescription>>}, +
_vertex_attribute_descriptions_: {<<vertexinputattributedescription, vertexinputattributedescription>>}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPipelineVertexInputStateCreateInfo[VkPipelineVertexInputStateCreateInfo])#


* [[vertexinputbindingdescription]]
[small]#*vertexinputbindingdescription* = { +
_binding_: integer, +
_stride_: integer, +
_input_rate_: <<vertexinputrate, vertexinputrate>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkVertexInputBindingDescription[VkVertexInputBindingDescription])#

* [[vertexinputattributedescription]]
[small]#*vertexinputattributedescription* = { +
_binding_: integer, +
_location_: integer, +
_format_: <<format, format>>, +
_offset_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkVertexInputAttributeDescription[VkVertexInputAttributeDescription])#

* [[pipelineinputassemblystatecreateinfo]]
[small]#*pipelineinputassemblystatecreateinfo* = { +
_flags_: <<pipelineinputassemblystatecreateflags, pipelineinputassemblystatecreateflags>>, +
_topology_: <<primitivetopology, primitivetopology>>, +
_primitive_restart_enable_: boolean, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPipelineInputAssemblyStateCreateInfo[VkPipelineInputAssemblyStateCreateInfo])#


* [[pipelinetessellationstatecreateinfo]]
[small]#*pipelinetessellationstatecreateinfo* = { +
_flags_: <<pipelinetessellationstatecreateflags, pipelinetessellationstatecreateflags>>, +
_patch_control_points_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPipelineTessellationStateCreateInfo[VkPipelineTessellationStateCreateInfo])#


* [[pipelineviewportstatecreateinfo]]
[small]#*pipelineviewportstatecreateinfo* = { +
_flags_: <<pipelineviewportstatecreateflags, pipelineviewportstatecreateflags>>, +
_viewports_: {<<viewport, viewport>>}, +
_scissors_: {<<rect2d, rect2d>>}, +
_viewport_count_: integer (forced to #_viewports_, if given, or defaults to 1), +
_scissor_count_: integer (forced to #_scissors_, if given, or defaults to 1), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPipelineViewportStateCreateInfo[VkPipelineViewportStateCreateInfo])#


* [[pipelinerasterizationstatecreateinfo]]
[small]#*pipelinerasterizationstatecreateinfo* = { +
_flags_: <<pipelinerasterizationstatecreateflags, pipelinerasterizationstatecreateflags>>, +
_depth_clamp_enable_: boolean, +
_rasterizer_discard_enable_: boolean, +
_polygon_mode_: <<polygonmode, polygonmode>>, +
_cull_mode_: <<cullmodeflags, cullmodeflags>>, +
_front_face_: <<frontface, frontface>>, +
_depth_bias_enable_: boolean, +
_depth_bias_constant_factor_: float, +
_depth_bias_clamp_: float, +
_depth_bias_slope_factor_: float, +
_line_width_: float (defaults to 1.0), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPipelineRasterizationStateCreateInfo[VkPipelineRasterizationStateCreateInfo])#


* [[pipelinemultisamplestatecreateinfo]]
[small]#*pipelinemultisamplestatecreateinfo* = { +
_flags_: <<pipelinemultisamplestatecreateflags, pipelinemultisamplestatecreateflags>>, +
_rasterization_samples_: <<samplecountflags, samplecountflags>> (defaults to 1), +
_sample_shading_enable_: boolean, +
_min_sample_shading_: float, +
_alpha_to_coverage_enable_: boolean, +
_alpha_to_one_enable_: boolean, +
_sample_mask_: {integer}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPipelineMultisampleStateCreateInfo[VkPipelineMultisampleStateCreateInfo])#


* [[pipelinedepthstencilstatecreateinfo]]
[small]#*pipelinedepthstencilstatecreateinfo* = { +
_flags_: <<pipelinedepthstencilstatecreateflags, pipelinedepthstencilstatecreateflags>>, +
_depth_test_enable_: boolean, +
_depth_write_enable_: boolean, +
_depth_compare_op_: <<compareop, compareop>>, +
_depth_bounds_test_enable_: boolean, +
_stencil_test_enable_: boolean, +
_front_: <<stencilopstate, stencilopstate>>, +
_back_: <<stencilopstate, stencilopstate>>, +
_min_depth_bounds_: float, +
_max_depth_bounds_: float, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPipelineDepthStencilStateCreateInfo[VkPipelineDepthStencilStateCreateInfo])#

* [[stencilopstate]]
[small]#*stencilopstate* = { +
_fail_op_: <<stencilop, stencilop>>, +
_pass_op_: <<stencilop, stencilop>>, +
_depth_fail_op_: <<stencilop, stencilop>>, +
_compare_op_: <<compareop, compareop>>, +
_compare_mask_: integer, +
_write_mask_: integer, +
_reference_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkStencilOpState[VkStencilOpState])#


* [[pipelinecolorblendstatecreateinfo]]
[small]#*pipelinecolorblendstatecreateinfo* = { +
_flags_: <<pipelinecolorblendstatecreateflags, pipelinecolorblendstatecreateflags>>, +
_logic_op_enable_: boolean, +
_logic_op_: <<logicop, logicop>>, +
_attachments_: {<<pipelinecolorblendattachmentstate, pipelinecolorblendattachmentstate>>}, +
_blend_constants_: {float} (length=4), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPipelineColorBlendStateCreateInfo[VkPipelineColorBlendStateCreateInfo])#

* [[pipelinecolorblendattachmentstate]]
[small]#*pipelinecolorblendattachmentstate* = { +
_blend_enable_: boolean, +
_src_color_blend_factor_: <<blendfactor, blendfactor>>, +
_dst_color_blend_factor_: <<blendfactor, blendfactor>>, +
_color_blend_op_: <<blendop, blendop>>, +
_src_alpha_blend_factor_: <<blendfactor, blendfactor>>, +
_dst_alpha_blend_factor_: <<blendfactor, blendfactor>>, +
_alpha_blend_op_: <<blendop, blendop>>, +
_color_write_mask_: <<colorcomponentflags, colorcomponentflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPipelineColorBlendAttachmentState[VkPipelineColorBlendAttachmentState])#

* [[pipelinecolorblendadvancedstatecreateinfo]]
[small]#*pipelinecolorblendadvancedstatecreateinfo* = { +
_src_premultiplied_: boolean, +
_dst_premultiplied_: boolean, +
_blend_overlap_: <<blendoverlap, blendoverlap>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPipelineColorBlendAdvancedStateCreateInfoEXT[VkPipelineColorBlendAdvancedStateCreateInfoEXT])#

* [[pipelinediscardrectanglestatecreateinfo]]
[small]#*pipelinediscardrectanglestatecreateinfo* = { +
_flags_: <<discardrectangleflags, discardrectangleflags>>, +
_discard_rectangle_mode_: <<discardrectanglemode, discardrectanglemode>> *[R]*, +
_discard_rectangles_: {<<rect2d, rect2d>>}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPipelineDiscardRectangleStateCreateInfoEXT[VkPipelineDiscardRectangleStateCreateInfoEXT])#

* [[pipelinedynamicstatecreateinfo]]
[small]#*pipelinedynamicstatecreateinfo* = { +
_flags_: <<pipelinedynamicstatecreateflags, pipelinedynamicstatecreateflags>>, +
_dynamic_states_: {<<dynamicstate, dynamicstate>>} *[R]*, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPipelineDynamicStateCreateInfo[VkPipelineDynamicStateCreateInfo])#


* [[buffercopy]]
[small]#*buffercopy* = { +
_src_offset_: integer, +
_dst_offset_: integer, +
_size_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkBufferCopy[VkBufferCopy])#

* [[imagecopy]]
[small]#*imagecopy* = { +
_src_subresource_: <<imagesubresourcelayers, imagesubresourcelayers>> *[R]*, +
_dst_subresource_: <<imagesubresourcelayers, imagesubresourcelayers>> *[R]*, +
_src_offset_: <<offset3d, offset3d>>, +
_dst_offset_: <<offset3d, offset3d>>, +
_extent_: <<extent3d, extent3d>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkImageCopy[VkImageCopy])#


* [[imageblit]]
[small]#*imageblit* = { +
_src_subresource_: <<imagesubresourcelayers, imagesubresourcelayers>> *[R]*, +
_dst_subresource_: <<imagesubresourcelayers, imagesubresourcelayers>> *[R]*, +
_src_offsets_: {<<offset3d, offset3d>>} (length = 2), +
_dst_offsets_: {<<offset3d, offset3d>>} (length = 2), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkImageBlit[VkImageBlit])#

* [[imagesubresourcelayers]]
[small]#*imagesubresourcelayers* = { +
_aspect_flags_: <<imageaspectflags, imageaspectflags>>, +
_mip_level_: integer, +
_base_array_layer_: integer, +
_layer_count_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkImageSubresourceLayers[VkImageSubresourceLayers]) +
<<constructors, Constructor>>: *imagesubresourcelayers*(_aspect_mask_, _mip_level_, _base_array_layer_, _layer_count_)#

* [[bufferimagecopy]]
[small]#*bufferimagecopy* = { +
_buffer_offset_: integer, +
_buffer_row_length_: integer, +
_buffer_image_height_: integer, +
_image_subresource_: <<imagesubresourcelayers, imagesubresourcelayers>> *[R]*, +
_image_offset_: <<offset3d, offset3d>>, +
_image_extent_: <<extent3d, extent3d>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkBufferImageCopy[VkBufferImageCopy])#

* [[imageresolve]]
[small]#*imageresolve* = { +
_src_subresource_: <<imagesubresourcelayers, imagesubresourcelayers>> *[R]*, +
_dst_subresource_: <<imagesubresourcelayers, imagesubresourcelayers>> *[R]*, +
_src_offset_: <<offset3d, offset3d>>, +
_dst_offset_: <<offset3d, offset3d>>, +
_extent_: <<extent3d, extent3d>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkImageResolve[VkImageResolve])#

* [[memorybarrier]]
[small]#*memorybarrier* = { +
_src_access_mask_: <<accessflags, accessflags>>, +
_dst_access_mask_: <<accessflags, accessflags>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkMemoryBarrier[VkMemoryBarrier])#

* [[buffermemorybarrier]]
[small]#*buffermemorybarrier* = { +
_src_access_mask_: <<accessflags, accessflags>>, +
_dst_access_mask_: <<accessflags, accessflags>>, +
_src_queue_family_index_: integer (default: ignored), +
_dst_queue_family_index_: integer (default: ignored), +
_buffer_: <<buffer, buffer>> *[R]*, +
_offset_: integer, +
_size_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkBufferMemoryBarrier[VkBufferMemoryBarrier])#

* [[imagememorybarrier]]
[small]#*imagememorybarrier* = { +
_src_access_mask_: <<accessflags, accessflags>>, +
_dst_access_mask_: <<accessflags, accessflags>>, +
_src_queue_family_index_: integer (default: ignored), +
_dst_queue_family_index_: integer (default: ignored), +
_old_layout_: <<imagelayout, imagelayout>>, +
_new_layout_: <<imagelayout, imagelayout>>, +
_image_: <<image, image>>, +
_subresource_range_: <<imagesubresourcerange, imagesubresourcerange>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkImageMemoryBarrier[VkImageMemoryBarrier])#

'''

* [[viewport]]
[small]#*viewport* = { +
_x_, _y_, _width_, _height_, _min_depth_, _max_depth_: float, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkViewport[VkViewport]) +
<<constructors, Constructor>>: *viewport*(_x_, _y_, _width_, _height_, _min_depth_, _max_depth_)#

* [[offset2d]]
[small]#*offset2d* = { +
_x_, _y_: integer +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkOffset2D[VkOffset2D]) +
<<constructors, Constructor>>: *offset2d*(_x_, _y_)#

* [[offset3d]]
[small]#*offset3d* = { +
_x_, _y_, _z_: integer +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkOffset3D[VkOffset3D]) +
<<constructors, Constructor>>: *offset3d*(_x_, _y_, _z_)#

* [[extent2d]]
[small]#*extent2d* = { +
_width_, _height_: integer +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkExtent2D[VkExtent2D]) +
<<constructors, Constructor>>: *extent2d*(_width_, _height_)#

* [[extent3d]]
[small]#*extent3d* = { +
_width_, _height_, _depth_: integer +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkExtent3D[VkExtent3D]) +
<<constructors, Constructor>>: *extent3d*(_width_, _height_, _depth_)#

* [[rect2d]]
[small]#*rect2d* = { +
_offset_: <<offset2d, offset2d>>, +
_extent_: <<extent2d, extent2d>> +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkRect2D[VkRect2D]) +
<<constructors, Constructor>>: *rect2d*(_x_, _y_, _width_, _height_)#

* [[componentmapping]]
[small]#*componentmapping* = { +
_r_, _g_, _b_, _a_: <<componentswizzle, componentswizzle>> +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkComponentMapping[VkComponentMapping]) +
<<constructors, Constructor>>: *componentmapping*(_r_, _g_, _b_, _a_)#


* [[clearcolorvalue]]
[small]#*clearcolorvalue* = { +
_[1],[2],[3],[4]_: float *|* +
_[1],[2],[3],[4]_: float, _t_='_float32_' *|* +
_[1],[2],[3],[4]_: integer, _t_='_uint32_' *|* +
_[1],[2],[3],[4]_: integer, _t_='_int32_' + 
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkClearColorValue[VkClearColorValue])#

* [[clearvalue]]
[small]#*clearvalue* = { +
_color_: <<clearcolorvalue, clearcolorvalue>> *|* +
_depth_: float, _stencil_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkClearValue[VkClearValue]). +
See also the <<clearcolor_snippet, example>> in the code snippets section.#


* [[clearattachment]]
[small]#*clearattachment* = { +
_aspect_mask_: <<imageaspectmask, imageaspectmask>>, +
_color_attachment_: integer or '_unused_' (defaults to '_unused_'), +
_clear_value_: <<clearvalue, clearvalue>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkClearAttachment[VkClearAttachment])#

* [[clearrect]]
[small]#*clearrect* = { +
_rect_: <<rect2d, rect2d>>, +
_base_array_layer_: integer, +
_layer_count_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkClearRect[VkClearRect])#


* [[renderpassbegininfo]]
[small]#*renderpassbegininfo* = { +
_render_pass_: <<render_pass, render_pass>> *[R]*, +
_framebuffer_: <<framebuffer, framebuffer>> *[R]*, +
_render_area_: <<rect2d, rect2d>>, +
_clear_values_: {<<clearvalue, clearvalue>>}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkRenderPassBeginInfo[VkRenderPassBeginInfo])#

'''

* [[surfacecapabilities]]
[small]#*surfacecapabilities* = { +
_min_image_count_: integer, +
_max_image_count_: integer, +
_current_extent_: <<extent2d, extent2d>> (=_nil_ if undefined, see Note1 below), +
_min_image_extent_: <<extent2d, extent2d>>, +
_max_image_extent_: <<extent2d, extent2d>>, +
_max_image_array_layers_: integer, +
_supported_transforms_: <<surfacetransformflags, surfacetransformflags>>, +
_current_transform_: <<surfacetransformflags, surfacetransformflags>>, +
_supported_composite_alpha_: <<compositealphaflags, compositealphaflags>>, +
_supported_usage_flags_: <<imageusageflags, imageusageflags>>, +
pass:[----] extensions ---- +
_shared_present_supported_usage_flags_: <<imageusageflags, imageusageflags>> (Note2), +
_supported_surface_counters_: <<surfacecounterflags, _surfacecounterflags_>> (Note3), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSurfaceCapabilities2KHR[VkSurfaceCapabilities2KHR]) +
Note1: The _current_extent_ field is _nil_ when _width_ and _height_ in the underlying C struct have the special value 0xFFFFFFFF. +
Note2: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_get_surface_capabilities2[VK_KHR_get_surface_capabilities2] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSharedPresentSurfaceCapabilitiesKHR[VkSharedPresentSurfaceCapabilitiesKHR]). +
Note3: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_EXT_display_surface_counter[VK_EXT_display_surface_counter] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPhysicalDeviceSurfaceCapabilities2EXT[VkPhysicalDeviceSurfaceCapabilities2EXT]).#

* [[surfaceformat]]
[small]#*surfaceformat* = { +
_format_: <<format, format>>, +
_color_space_: <<colorspace, colorspace>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSurfaceFormat2KHR[VkSurfaceFormat2KHR])#

'''


* [[swapchaincreateinfo]]
[small]#*swapchaincreateinfo* = { +
_flags_: <<swapchaincreateflags, swapchaincreateflags>>, +
_surface_: <<surface, surface>> *[R]*, +
_min_image_count_: integer, +
_image_format_: <<format, format>>, +
_image_color_space_: <<colorspace, colorspace>>, +
_image_extent_: <<extent2d, extent2d>>, +
_image_array_layers_: integer, +
_image_usage_: <<imageusageflags, imageusageflags>>, +
_image_sharing_mode_: <<sharingmode, sharingmode>>, +
_queue_family_indices_: {integer}, +
_pre_transform_: <<surfacetransformflags, surfacetransformflags>>, +
_composite_alpha_: <<compositealphaflags, compositealphaflags>>, +
_present_mode_: <<presentmode, presentmode>>, +
_clipped_: boolean, +
_old_swapchain_: <<swapchain, swapchain>>, +
pass:[----] extensions ---- +
_surface_counters_: <<surfacecounterflags, surfacecounterflags>> (Note1), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSwapchainCreateInfoKHR[VkSwapchainCreateInfoKHR]) +
Note1: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_EXT_display_control[VK_EXT_display_control] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkSwapchainCounterCreateInfoEXT[VkSwapchainCounterCreateInfoEXT]).#



* [[presentinfo]]
[small]#*presentinfo* = { +
_swapchains_: {<<swapchain, swapchain>>}, +
_image_indices_: {integer} (same length as _swapchains_), +
_wait_semaphores_: {<<semaphore, semaphore>>}, +
pass:[----] extensions ---- +
_src_rect_: <<extent2d, extent2d>> (Note1), +
_dst_rect_: <<extent2d, extent2d>> (Note1), +
_persistent_: boolean (Note1), +
_regions_: {<<presentregion, presentregion>>} (Note2), +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPresentInfoKHR[VkPresentInfoKHR]), +
Note1: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_display_swapchain[VK_KHR_display_swapchain] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDisplayPresentInfoKHR[VkDisplayPresentInfoKHR]). +
Note2: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_incremental_present[VK_KHR_incremental_present] extension (rfr:
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPresentRegionsKHR[VkPresentRegionsKHR]).#

* [[presentregion]]
[small]#*presentregion* = { +
_rectangles_: {<<rectlayer, rectlayer>>}, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPresentRegionKHR[VkPresentRegionKHR])#

* [[rectlayer]]
[small]#*rectlayer* = { +
_offset_: <<offset2d, offset2d>> *[R]*, +
_extent_: <<extent2d, extent2d>> *[R]*, +
_layer_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkRectLayerKHR[VkRectLayerKHR])#

'''

* [[hdrmetadata]]
[small]#*hdrmetadata* = { +
_display_primary_red_: <<xycolor, xycolor>>, +
_display_primary_green_: <<xycolor, xycolor>>, +
_display_primary_blue_: <<xycolor, xycolor>>, +
_white_point_: <<xycolor, xycolor>>, +
_max_luminance_: number, +
_min_luminance_: number, +
_max_content_light_level_: number, +
_max_frame_average_light_level_: number, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkHdrMetadataEXT[VkHdrMetadataEXT])#

* [[xycolor]]
[small]#*xycolor* = { +
_x_, _y_: number, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkXYColorEXT[VkXYColorEXT])#

'''

* [[displaypowerinfo]]
[small]#*displaypowerinfo* = { +
_power_state_: <<displaypowerstate, displaypowerstate>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDisplayPowerInfoEXT[VkDisplayPowerInfoEXT])#


* [[displayproperties]]
[small]#*displayproperties* = { +
_display_: <<display, display>>, +
_display_name_: string, +
_physical_dimensions_: <<extent2d, extent2d>>, +
_physical_resolution_: <<extent2d, extent2d>>, +
_supported_transforms_: <<surfacetransformflags, surfacetransformflags>>, +
_plane_reorder_possible_: boolean, +
_persistent_content_: boolean, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDisplayPropertiesKHR[VkDisplayPropertiesKHR])#

* [[displayplaneproperties]]
[small]#*displayplaneproperties* = { +
_current_display_: <<display, display>> (may be _nil_), +
_current_stack_index_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDisplayPlanePropertiesKHR[VkDisplayPlanePropertiesKHR])#

* [[displaymodeproperties]]
[small]#*displaymodeproperties* = { +
_display_mode_: <<display_mode, display_mode>>, +
_parameters_: <<displaymodeparameters, displaymodeparameters>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDisplayModePropertiesKHR[VkDisplayModePropertiesKHR])#

* [[displaymodeparameters]]
[small]#*displaymodeparameters* = { +
_visible_region_: <<extent2d, extent2d>> *[R]*, +
_refresh_rate_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDisplayModeParametersKHR[VkDisplayModeParametersKHR])#

* [[displayplanecapabilities]]
[small]#*displayplanecapabilities* = { +
_supported_alpha_: <<displayplanealphaflags, displayplanealphaflags>>, +
_min_src_position_: <<offset2d, offset2d>>, +
_max_src_position_: <<offset2d, offset2d>>, +
_min_src_extent_: <<extent2d, extent2d>>, +
_max_src_extent_: <<extent2d, extent2d>>, +
_min_dst_position_: <<offset2d, offset2d>>, +
_max_dst_position_: <<offset2d, offset2d>>, +
_min_dst_extent_: <<extent2d, extent2d>>, +
_max_dst_extent_: <<extent2d, extent2d>>, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDisplayPlaneCapabilitiesKHR[VkDisplayPlaneCapabilitiesKHR])#

* [[displaysurfacecreateinfo]]
[small]#*displaysurfacecreateinfo* = { +
_flags_: <<displaysurfacecreateflags, displaysurfacecreateflags>>, +
_plane_index_: integer, +
_plane_stack_index_: integer, +
_transform_: <<surfacetransformflags, surfacetransformflags>>, +
_global_alpha_: float, +
_alpha_mode_: <<displayplanealphaflags, displayplanealphaflags>>, +
_image_extent_: <<extent2d, extent2d>> *[R]*, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDisplaySurfaceCreateInfoKHR[VkDisplaySurfaceCreateInfoKHR])#

'''

* [[descriptorupdatetemplatecreateinfo]]
[small]#*descriptorupdatetemplatecreateinfo* = { +
_flags_: <<descriptorupdatetemplatecreateflags, descriptorupdatetemplatecreateflags>>, +
_descriptor_update_entries_: {<<descriptorupdatetemplateentry, descriptorupdatetemplateentry>>}, +
_template_type_: <<descriptorupdatetemplatetype, descriptorupdatetemplatetype>> *[R]*, +
_descriptor_set_layout_: <<descriptor_set_layout, descriptor_set_layout>>, +
_pipeline_bind_point_: <<pipelinebindpoint, pipelinebindpoint>>, +
_pipeline_layout_: <<pipeline_layout, pipeline_layout>>, +
_set_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDescriptorUpdateTemplateCreateInfoKHR[VkDescriptorUpdateTemplateCreateInfoKHR])#

* [[descriptorupdatetemplateentry]]
[small]#*descriptorupdatetemplateentry* = { +
_dst_binding_: integer, +
_dst_array_element_: integer, +
_descriptor_count_: integer, +
_descriptor_type_: <<descriptortype, descriptortype>> *[R]*, +
_offset_: integer, +
_stride_: integer, +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkDescriptorUpdateTemplateEntryKHR[VkDescriptorUpdateTemplateEntryKHR])#


////
5yy
* [[]]
[small]#** = { +
@@TODO +
} (rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#Vk[])#

__: string, +
__: boolean, +
__: float, +
__: integer, +
__: <<, >>, +
__: {<<, >>}, +

////

