
[[swapchain]]
==== swapchain

The following functions require the 
https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_swapchain[VK_KHR_swapchain] device extension.

[[create_swapchain]]
* _swapchain_ = *create_swapchain*(<<device, _device_>>, <<swapchaincreateinfo, _swapchaincreateinfo_>>, [<<allocators, _allocator_>>]) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkCreateSwapchainKHR[vkCreateSwapchainKHR].#

[[create_shared_swapchains]]
* {_swapchain_} = *create_shared_swapchains*(<<device, _device_>>, {<<swapchaincreateinfo, _swapchaincreateinfo_>>}, [<<allocators, _allocator_>>]) +
[small]#This function requires the https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_display_swapchain[VK_KHR_display_swapchain] device extension. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkCreateSharedSwapchainsKHR[vkCreateSharedSwapchainsKHR].#

[[destroy_swapchain]]
* *destroy_swapchain*(_swapchain_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkDestroySwapchainKHR[vkDestroySwapchainKHR].#

[[get_swapchain_images]]
* {<<image, _image_>>} = *get_swapchain_images*(_swapchain_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkGetSwapchainImagesKHR[vkGetSwapchainImagesKHR].#

[[acquire_next_image]]
* _image_index_, _message_ = *acquire_next_image*(_swapchain_, <<timeout, _timeout_>>, [<<semaphore, _semaphore_>>], [<<fence, _fence_>>]) +
[small]#Returns one of the following combinations of _image_index_ and _message_: +
1) _integer_, _nil_ 2) _integer_, '_suboptimal_' 3) _nil_, '_timeout_'  4) _nil_, '_not ready_' +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkAcquireNextImageKHR[vkAcquireNextImageKHR].#

[[queue_present]]
* <<result, _result_>>, {<<result, _result_>>} = *queue_present*(<<queue, _queue_>>, <<presentinfo, _presentinfo_>>, [_per_swapchain_results_]) +
[small]#[_per_swapchain_results_]: boolean +
Returns the global _result_ for the operation, optionally followed by a table
with the individual results for each of the given swapchains. +
The individual results table is returned only if _per_swapchain_results_ is _true_. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkQueuePresentKHR[vkQueuePresentKHR].#

[[get_swapchain_status]]
* <<result, _result_>> = *get_swapchain_status*(_swapchain_) +
[small]#This function requires the https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_KHR_shared_presentable_image[VK_KHR_shared_presentable_image] device extension. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkGetSwapchainStatusKHR[vkGetSwapchainStatusKHR].#

[[set_hdr_metadata]]
* *set_hdr_metadata*({_swapchain_}, <<hdrmetadata, _hdrmetadata_>>) +
[small]#This function requires the https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_EXT_hdr_metadata[VK_EXT_hdr_metadata] device extension. +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkSetHdrMetadataEXT[vkSetHdrMetadataEXT].#

////
[[]]
* <<,__>> = **(_swapchain_) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkKHR[KHR].#

arg3 - __: integer +
arg3 - __: <<, >> +
arg3 - __: {<<, >>} +
arg3 - __: <<, >> (opt.) +
arg3 - __: {<<, >>} (opt.) +

////

