
[[versions]]
=== Version handling

[[enumerate_instance_version]]
* _version_ = *enumerate_instance_version*( ) +
[small]#Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkEnumerateInstanceVersion.html[vkEnumerateInstanceVersion].#

[[version]]
* _version_ = *make_version*(_major_, _minor_, _patch_, [_variant_=0]) +
[small]#Constructs _version_ (an integer) from _major_, _minor_, _patch_, and _variant_ numbers (also integers). +
Rfr: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#extendingvulkan-coreversions[Version Numbers].#

[[version_numbers]]
* _major_, _minor_, _patch_ = *version_numbers*(_version_) +
[small]#Extracts the _major_, _minor_, _patch_, and _variant_ numbers (integers) from _version_ (also an integer).#

[[version_string]]
* _string_ = *version_string*(_version_) +
[small]#Returns the '_x.y.z_' string for _version_ (an integer), where x, y, and z are the major, minor 
and patch numbers, respectively.#

The *vk* table contains also the following version related information:

* vk.*_VERSION*: MoonVulkan version (a string).
* vk.*API_VERSION_n_m*: Vulkan versions supported by MoonVulkan (e.g. vk.API_VERSION_1_0, vk.API_VERSION_2_0, ...).
* vk.*API_VERSIONS*: a table listing the supported versions as strings (e.g. { 'API_VERSION_1_0', 'API_VERSION_2_0', ... }).
* vk.*HEADER_VERSION*: Vulkan header version (VK_HEADER_VERSION). 
Note that this refers to the vulkan.h header that MoonVulkan is built against, which may not be 
aligned with the Vulkan implementation(s) installed on the system.

